const PLACES = [
    {
        id:'p1',
        name:'อ่างแก้ว มช.',
        alias:'นักพักผ่อนสายชิลริมอ่างแก้ว',
        cat:'natural',
        coins:40,
        xp:45,
        stars:4.2,
        dist:3.72,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.8022, lng:98.9524,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQwHXJzhR_vLrPwe8umWxy5DmaJKXLiQrCL_smTW2eFg&s=10',
        desc:'อ่างเก็บน้ำกลางมหาวิทยาลัยเชียงใหม่ บรรยากาศร่มรื่น เหมาะเดินเล่น ปั่นจักรยาน และนั่งพักผ่อน'
    },
    {
        id:'p2',
        name:'วัดพระธาตุดอยสุเทพราชวรวิหาร',
        alias:'ผู้แสวงบุญคู่เมืองเชียงใหม่',
        cat:'temple',
        coins:80,
        xp:100,
        stars:4.8,
        dist:9.50,
        price:'30 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.8047, lng:98.9212,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkIlsK5HN-Ukm5n1KMlYv0ZjB54q-kH1XwPvUvLzywTg&s=10',
        desc:'วัดคู่บ้านคู่เมืองเชียงใหม่ บนยอดดอยสุเทพ สถาปัตยกรรมล้านนาทองอร่ามและจุดชมวิวเมือง'
    },
    {
        id:'p3',
        name:'ถนนคนเดินท่าแพ',
        alias:'นักช้อปสายสตรีทไลฟ์',
        cat:'village',
        coins:50,
        xp:60,
        stars:4.6,
        dist:1.20,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7885, lng:98.9912,
        img:'https://www.cmcity.go.th/data/content/2020/8198/cms/big/image_cms_fgnpsyz13468.jpg',
        desc:'ถนนคนเดินยอดฮิตวันอาทิตย์ เต็มไปด้วยสินค้าแฮนด์เมด งานฝีมือ และอาหารพื้นเมือง'
    },
    {
        id:'p4',
        name:'วัดเจดีย์หลวงวรวิหาร',
        alias:'นักสำรวจโบราณสถานเก่าแก่',
        cat:'temple',
        coins:60,
        xp:70,
        stars:4.7,
        dist:0.80,
        price:'40 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7877, lng:98.9873,
        img:'https://image-tc.galaxy.tf/wijpeg-e07rgtlimh9ajqyiylwv7r49t/wat-chedi-luang_standard.jpg?crop=112%2C0%2C1777%2C1333',
        desc:'วัดโบราณใจกลางเมืองเก่า มีองค์เจดีย์ขนาดใหญ่ที่แม้จะหักพังไปตามกาลเวลาแต่ก็ยังคงความยิ่งใหญ่'
    },
    {
        id:'p5',
        name:'วัดพระสิงห์วรมหาวิหาร',
        alias:'ผู้ศรัทธาศิลปะล้านนา',
        cat:'temple',
        coins:60,
        xp:70,
        stars:4.7,
        dist:1.10,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7888, lng:98.9818,
        img:'https://upload.wikimedia.org/wikipedia/commons/6/6c/Wat_Phra_Sing%2C_Chiang_Mai_%28I%29.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'วัดสำคัญที่ประดิษฐานพระพุทธสิหิงค์ พระพุทธรูปสำคัญคู่เมืองเชียงใหม่และแผ่นดินล้านนา'
    },
    {
        id:'p6',
        name:'ตลาดวโรรส (กาดหลวง)',
        alias:'นักชิมตลาดพื้นเมือง',
        cat:'village',
        coins:40,
        xp:50,
        stars:4.5,
        dist:1.50,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7905, lng:98.9984,
        img:'https://palanla.com/ckeditor/upload/files/id37/abroad_location/Warors%20Market/001.jpg',
        desc:'ตลาดเก่าแก่ที่สุดในเชียงใหม่ แหล่งรวมของฝากขึ้นชื่อ เช่น น้ำพริกหนุ่ม แคบหมู และไส้อั่ว'
    },
    {
        id:'p7',
        name:'คลองแม่ข่า',
        alias:'ผู้เดินเล่นคลองโอทอปสไตล์ญี่ปุ่น',
        cat:'natural',
        coins:45,
        xp:50,
        stars:4.3,
        dist:1.90,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7954, lng:98.9972,
        img:'https://upload.wikimedia.org/wikipedia/commons/8/8b/Khlong_Mae_Kha_bridge_1_IMG_20230225_172228.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'คลองระบายน้ำที่ถูกพลิกโฉมเป็นแหล่งท่องเที่ยวสไตล์ญี่ปุ่น มีร้านค้าและมุมถ่ายรูปสุดชิค'
    },
    {
        id:'p8',
        name:'วัดอุโมงค์ (สวนธรรม)',
        alias:'ผู้แสวงความสงบในอุโมงค์โบราณ',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.6,
        dist:4.20,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7831, lng:98.9554,
        img:'https://upload.wikimedia.org/wikipedia/commons/b/b3/Wat_Umong_%28I%29.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'วัดป่าร่มรื่นที่มีอุโมงค์โบราณอายุหลายร้อยปี บรรยากาศเงียบสงบเหมาะแก่การปฏิบัติธรรม'
    },
    {
        id:'p9',
        name:'วันนิมมาน (One Nimman)',
        alias:'นักช้อปไลฟ์สไตล์คอมมูนิตี้',
        cat:'village',
        coins:50,
        xp:60,
        stars:4.5,
        dist:3.20,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7979, lng:98.9681,
        img:'https://img.wongnai.com/p/400x0/2018/10/25/ed82820a0e2c493093ae9fe6837e59ee.jpg',
        desc:'แหล่งรวมสินค้าแฮนด์เมด งานดีไซน์ และร้านอาหารสไตล์ยุโรปผสมล้านนาใจกลางนิมมาน'
    },
    {
        id:'p10',
        name:'สวนสัตว์เชียงใหม่',
        alias:'นักท่องเที่ยวสายรักสัตว์',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.3,
        dist:5.10,
        price:'150 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.8115, lng:98.9472,
        img:'https://upload.wikimedia.org/wikipedia/commons/2/29/Chiangmai-zoo01.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'สวนสัตว์ขนาดใหญ่เชิงดอยสุเทพ จัดแสดงสัตว์นานาชนิดและอควาติดัมยักษ์'
    },
    {
        id:'p11',
        name:'พิพิธภัณฑ์พื้นถิ่นล้านนา',
        alias:'นักอนุรักษ์วัฒนธรรมพื้นบ้าน',
        cat:'village',
        coins:40,
        xp:45,
        stars:4.4,
        dist:1.00,
        price:'20 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7891, lng:98.9892,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYZAT-c_74NMRdd_vbzlqT099zG8jH-KKXW22yq3q160E7bcSaQkqVy1Qf&s=10',
        desc:'แหล่งเรียนรู้ประวัติศาสตร์ วิถีชีวิต และศิลปวัฒนธรรมดั้งเดิมของชาวล้านนา'
    },
    {
        id:'p12',
        name:'วัดโลกโมฬี',
        alias:'นักเที่ยวสายมูขอพรความรัก',
        cat:'temple',
        coins:45,
        xp:50,
        stars:4.6,
        dist:1.60,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7942, lng:98.9850,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVqHU0P73emDguhTjBe0QvT_GHnAwlnHK_JxvmlmTd4xbD3Hraf3UAzcg1&s=10',
        desc:'วัดโบราณในเขตเมืองเก่า มีพระวิหารไม้สักแกะสลักงดงามและพระเจดีย์โบราณ'
    },
    {
        id:'p13',
        name:'กาดทุ่งเกวียน (เชียงใหม่-ลำปาง / โซนใกล้เคียง)',
        alias:'นักชิมของป่าและของฝาก',
        cat:'village',
        coins:35,
        xp:40,
        stars:4.2,
        dist:15.00,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.5200, lng:99.1200,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMFAb-mKbtgBB3Osibafh1LNHBZjxlM_4o6iqxjhJ502ZtrYJdlQ3SAQE&s=10',
        desc:'ตลาดสินค้าพื้นบ้านและของฝากขึ้นชื่อของภาคเหนือ'
    },
    {
        id:'p14',
        name:'บ้านข้างวัด',
        alias:'ศิลปินอินดี้ชุมชนอาร์ต',
        cat:'village',
        coins:45,
        xp:55,
        stars:4.6,
        dist:4.80,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7752, lng:98.9531,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1Fnd6hYE3GM_tMBP9xHdAsZdooFE3FK5BDygpy0KyFT1F9SL8YseeXNtM&s=10',
        desc:'คอมมูนิตี้มอลล์สไตล์กึ่งบ้านสวน งานคราฟต์ งานศิลปะ และร้านกาแฟสุดอบอุ่น'
    },
    {
        id:'p15',
        name:'คาเฟ่ Chom Cafe and Restaurant',
        alias:'นักชิมในป่าหิมพานต์จำลอง',
        cat:'food',
        coins:70,
        xp:80,
        stars:4.5,
        dist:4.50,
        price:'200-500 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7562, lng:98.9684,
        img:'https://www.chomcafeandrestaurant.com/wp-content/uploads/2024/04/IMG1-1.webp',
        desc:'ร้านอาหารและคาเฟ่ชื่อดัง ตกแต่งสวนสวยร่มรื่นราวกับหลุดเข้าไปในป่าหิมพานต์มีหมอกและลำธาร'
    },
    {
        id:'p16',
        name:'วัดสวนดอก',
        alias:'ผู้ศึกษาประวัติศาสตร์กู่พระเจ้า',
        cat:'temple',
        coins:50,
        xp:60,
        stars:4.6,
        dist:2.10,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7865, lng:98.9754,
        img:'https://upload.wikimedia.org/wikipedia/commons/9/9b/%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%AA%E0%B8%A7%E0%B8%99%E0%B8%94%E0%B8%AD%E0%B8%81.JPG?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'วัดสำคัญที่มีกลุ่มสถูปบรรจุอัฐิเจ้าหลวงเชียงใหม่และพระประธานองค์ใหญ่'
    },
    {
        id:'p17',
        name:'หอศิลปวัฒนธรรมเมืองเชียงใหม่',
        alias:'นักท่องพิพิธภัณฑ์ประวัติศาสตร์',
        cat:'village',
        coins:40,
        xp:45,
        stars:4.4,
        dist:1.10,
        price:'20 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7902, lng:98.9881,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4PRjUM0FxL1n5aPnuJyPHK3HPlJFTw-FgJ-H_teGaBoZv54372nP3Ge0&s=10',
        desc:'พิพิธภัณฑ์รวบรวมเรื่องราวความเป็นมาของเมืองเชียงใหม่ตั้งแต่ยุคก่อตั้ง'
    },
    {
        id:'p18',
        name:'ตลาดธานินทร์',
        alias:'นักชิมสตรีทฟู้ดท้องถิ่น',
        cat:'food',
        coins:30,
        xp:35,
        stars:4.3,
        dist:2.50,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.8082, lng:98.9782,
        img:'https://img.wongnai.com/p/1920x0/2018/09/26/31f1376f605c4ff5b55910c581ec6f76.jpg',
        desc:'ตลาดสดและศูนย์รวมอาหารพื้นเมืองเชียงใหม่ที่คนท้องถิ่นนิยมมาซื้อหาของกิน'
    },
    {
        id:'p19',
        name:'วัดเชียงมั่น',
        alias:'ผู้กราบไหว้พระพุทธรูปปศิลากลางเมือง',
        cat:'temple',
        coins:50,
        xp:60,
        stars:4.6,
        dist:1.30,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7924, lng:98.9897,
        img:'https://upload.wikimedia.org/wikipedia/commons/6/6e/Wat_Chiang_Man_%28I%29.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'วัดที่เก่าแก่ที่สุดในตัวเมืองเชียงใหม่ สร้างขึ้นตั้งแต่สมัยพญามังราย'
    },
    {
        id:'p20',
        name:'พิพิธภัณฑ์แมลงโลกและสิ่งมหัศจรรย์ธรรมชาติ',
        alias:'นักสำรวจโลกแมลงจิ๋ว',
        cat:'natural',
        coins:40,
        xp:45,
        stars:4.1,
        dist:3.10,
        price:'100 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.8012, lng:98.9682,
        img:'https://files.thailandtourismdirectory.go.th/assets/upload/info/attraction/3310/20171023cfd12d07689acbaa573946b9dfd94e81010618.jpg',
        desc:'พิพิธภัณฑ์ส่วนตัวจัดแสดงสายพันธุ์แมลงและซากฟอสซิลแปลกตาในย่านนิมมาน'
    },

    // --- อำเภอ จอมทอง ---
    {
        id:'p21',
        name:'อุทยานแห่งชาติดอยอินทนนท์',
        alias:'ผู้พิชิตหลังคาประเทศไทย',
        cat:'natural',
        coins:120,
        xp:150,
        stars:4.9,
        dist:58.50,
        price:'50 บาท',
        zone:'อำเภอ จอมทอง',
        lat:18.5878, lng:98.4872,
        img:'https://img.kapook.com/u/2021/sutasinee/11/124.jpg',
        desc:'ยอดเขาที่สูงที่สุดในประเทศไทย อุดมไปด้วยป่าดิบเขา น้ำตก และอากาศหนาวเย็นตลอดปี'
    },
    {
        id:'p22',
        name:'น้ำตกวชิรธาร',
        alias:'ผู้ชื่นชมละอองน้ำยักษ์ดอยอินทนนท์',
        cat:'natural',
        coins:80,
        xp:90,
        stars:4.7,
        dist:45.20,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.5478, lng:98.6012,
        img:'https://upload.wikimedia.org/wikipedia/commons/0/05/Wachirathan_Falls.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'น้ำตกขนาดใหญ่สูงตระหง่านบนเส้นทางขึ้นดอยอินทนนท์ ละอองน้ำกระจายตัวกว้างขวาง'
    },
    {
        id:'p23',
        name:'พระมหาธาตุนภเมทนีดลและพระมหาธาตุนภพลภูมิสิริ',
        alias:'ผู้สักการะพระมหาธาตุคู่ฟ้า',
        cat:'temple',
        coins:90,
        xp:100,
        stars:4.8,
        dist:54.10,
        price:'40 บาท',
        zone:'อำเภอ จอมทอง',
        lat:18.5522, lng:98.4801,
        img:'https://cbtthailand.dasta.or.th/upload-file-api/Resources/RelateAttraction/Images/RAT500518/1.jpeg',
        desc:'พระมหาธาตุคู่บนยอดดอยอินทนนท์ ล้อมรอบด้วยสวนดอกไม้เมืองหนาวและวิวทิวทัศน์สุดอลังการ'
    },
    {
        id:'p24',
        name:'กิ่วแม่ปาน',
        alias:'นักเดินป่าล่าทะเลหมอกสุดขอบฟ้า',
        cat:'natural',
        coins:110,
        xp:140,
        stars:4.9,
        dist:56.30,
        price:'ค่าไกด์ท้องถิ่น',
        zone:'อำเภอ จอมทอง',
        lat:18.5564, lng:98.4805,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPE0arO3JuOM50BlyTF_K5-6VKMpCbrqDCbgb_BopYRE2s654J9pzWaAeB&s=10',
        desc:'เส้นทางศึกษาธรรมชาติระยะสั้นยอดฮิต วิวทะเลหมอกและทุ่งหญ้ากว้างบนสันเขา'
    },
    {
        id:'p25',
        name:'น้ำตกแม่ยะ',
        alias:'ผู้หลงใหลความงามน้ำตกชั้นลดหลั่น',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.6,
        dist:40.50,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.4112, lng:98.5089,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-GQ4cwcyGnObvutecrgGIHAG-3dZE-AJAZ52D_zUeug&s=10',
        desc:'น้ำตกขนาดใหญ่ที่ขึ้นชื่อว่ามีความงดงามมากที่สุดแห่งหนึ่งของอุทยานแห่งชาติดอยอินทนนท์'
    },
    {
        id:'p26',
        name:'วัดพระธาตุศรีจอมทองวรวิหาร',
        alias:'ผู้สักการะพระธาตุประจำปีเกิดปีชวด',
        cat:'temple',
        coins:65,
        xp:75,
        stars:4.7,
        dist:32.10,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.4354, lng:98.6782,
        img:'https://upload.wikimedia.org/wikipedia/commons/e/e8/%E0%B9%80%E0%B8%88%E0%B8%94%E0%B8%B5%E0%B8%A2%E0%B9%8C%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%98%E0%B8%B2%E0%B8%95%E0%B8%B8%E0%B8%A8%E0%B8%A3%E0%B8%B5%E0%B8%88%E0%B8%AD%E0%B8%A1%E0%B8%97%E0%B8%AD%E0%B8%87.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'วัดคู่บ้านคู่เมืองจอมทอง ประดิษฐานพระบรมสารีริกธาตุส่วนพระเศียรเบื้องขวา'
    },
    {
        id:'p27',
        name:'อ่างกา (เส้นทางศึกษาธรรมชาติอ่างกา)',
        alias:'นักท่องป่าดึกดำบรรพ์ลึกลับ',
        cat:'natural',
        coins:85,
        xp:95,
        stars:4.7,
        dist:59.00,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.5891, lng:98.4862,
        img:'https://adaymagazine.com/wp-content/uploads/2021/11/Nature-31-1024x684.jpg',
        desc:'ป่าดิบชื้นบนยอดดอยสูงสุด เต็มไปด้วยมอส เฟิร์น และกุหลาบพันปีโบราณ'
    },
    {
        id:'p28',
        name:'บ้านแม่กลางหลวง',
        alias:'นักท่องเที่ยววิถีชุมชนกลางนาข้าว',
        cat:'village',
        coins:80,
        xp:90,
        stars:4.6,
        dist:48.20,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.5412, lng:98.5321,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1u65m0iqGLSR4LWbwxpwkIPI7XebRO8UnnP_Za8w2Dj1LK9FG9VMQ4jA&s=10',
        desc:'หมู่บ้านชาวกระเหรี่ยงโปกะญอ ท่ามกลางนาขั้นบันไดและเสียงน้ำตกไหลผ่าน'
    },
    {
        id:'p29',
        name:'น้ำตกผาดอกเสี้ยว',
        alias:'นักผจญภัยตามรอยหนังรัก',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.5,
        dist:47.80,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.5422, lng:98.5281,
        img:'https://ngthai.com/app/uploads/2024/01/ph-egco.jpg',
        desc:'น้ำตกสวยหลายชั้นในเขตบ้านแม่กลางหลวง จุดถ่ายทำภาพยนตร์ชื่อดัง'
    },
    {
        id:'p30',
        name:'สวนดอกไม้ไฮเดรนเยียอินทนนท์',
        alias:'คนรักทุ่งดอกไม้สีฟ้าคราม',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.6,
        dist:50.10,
        price:'50 บาท',
        zone:'อำเภอ จอมทอง',
        lat:18.5381, lng:98.5211,
        img:'https://s359.kapook.com/pagebuilder/0f4b1b7e-00f7-46c0-a9be-c198d8ecc226.jpg',
        desc:'แปลงปลูกดอกไฮเดรนเยียขนาดใหญ่ บานสะพรั่งท่ามกลางหุบเขาบนดอยอินทนนท์'
    },

    // --- อำเภอ แม่แจ่ม ---
    {
        id:'p31',
        name:'บ้านป่าบงเปียง',
        alias:'ช่างภาพสายนาขั้นบันไดในตำนาน',
        cat:'village',
        coins:130,
        xp:160,
        stars:4.9,
        dist:78.00,
        price:'ฟรี',
        zone:'อำเภอ แม่แจ่ม',
        lat:18.5154, lng:98.3972,
        img:'https://img.kapook.com/u/2017/sutasinee/08/p1_1.jpg',
        desc:'นาขั้นบันไดที่สวยที่สุดในประเทศไทย โอบล้อมด้วยขุนเขาและสายหมอกยามเช้า'
    },
    {
        id:'p32',
        name:'นาขั้นบันไดบ้านกองกาน',
        alias:'นักท่องเที่ยววิถีชีวิตเงียบสงบ',
        cat:'village',
        coins:70,
        xp:80,
        stars:4.4,
        dist:72.50,
        price:'ฟรี',
        zone:'อำเภอ แม่แจ่ม',
        lat:18.4951, lng:98.3712,
        img:'https://img.wongnai.com/p/1920x0/2022/04/23/e7557fe2d1094753948b7666866e8c89.jpg',
        desc:'หมู่บ้านและทุ่งนาขั้นบันไดอันเงียบสงบในอำเภอแม่แจ่ม ห่างไกลความวุ่นวาย'
    },
    {
        id:'p33',
        name:'วัดกองกาน',
        alias:'ผู้กราบพระเจ้าทันใจแม่แจ่ม',
        cat:'temple',
        coins:60,
        xp:70,
        stars:4.5,
        dist:72.10,
        price:'ฟรี',
        zone:'อำเภอ แม่แจ่ม',
        lat:18.4982, lng:98.3741,
        img:'https://cbtthailand.dasta.or.th/upload-file-api/Resources/RelateAttraction/Images/RAT500476/1.jpeg',
        desc:'วัดเก่าแก่ที่มีพระพุทธรูปปูนปั้นงดงาม สถาปัตยกรรมแบบไทใหญ่ผสมล้านนา'
    },
    {
        id:'p34',
        name:'จุดชมวิวดอยปู่หมื่น',
        alias:'นักเดินทางสายออฟโรดชมวิวทะเลหมอก',
        cat:'natural',
        coins:90,
        xp:110,
        stars:4.6,
        dist:85.00,
        price:'ฟรี',
        zone:'อำเภอ แม่แจ่ม',
        lat:18.6121, lng:98.3512,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2cyTljn7UXrsfj1EGs0kxQ2uV99dtgLfeuExrrN2yPuuPi0BLGTbPekzb&s=10',
        desc:'จุดชมวิวบนยอดดอยสูงในแม่แจ่ม สัมผัสวิถีชุมชนและไร่ชาบนดอยสูง'
    },
    {
        id:'p35',
        name:'วัดพุทธεν (วัดยางหลวง)',
        alias:'ผู้ชื่นชมจิตรกรรมฝาผนังโบราณ',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.4,
        dist:70.20,
        price:'ฟรี',
        zone:'อำเภอ แม่แจ่ม',
        lat:18.4812, lng:98.3921,
        img:'https://upload.wikimedia.org/wikipedia/commons/7/71/%E0%B9%82%E0%B8%9A%E0%B8%AA%E0%B8%96%E0%B9%8C%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%A2%E0%B8%B2%E0%B8%87%E0%B8%AB%E0%B8%A5%E0%B8%A7%E0%B8%87.JPG?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'วัดเก่าแก่ที่มีหอไตรและวิหารไม้โบราณ ลวดลายแกะสลักล้านนาอันทรงคุณค่า'
    },

    // --- อำเภอ เชียงดาว ---
    {
        id:'p36',
        name:'ดอยหลวงเชียงดาว',
        alias:'นักปีนเขาสายพิชิตยอดดอยหินปูน',
        cat:'natural',
        coins:140,
        xp:180,
        stars:4.9,
        dist:71.20,
        price:'ค่าธรรมเนียมอุทยาน',
        zone:'อำเภอ เชียงดาว',
        lat:19.3512, lng:98.9412,
        img:'https://upload.wikimedia.org/wikipedia/commons/c/c7/Doi_Chiang_Dao_%28I%29.jpg?utm_source=th.wikipedia.org&utm_campaign=index&utm_content=original',
        desc:'ยอดดอยหินปูนสูงอันดับ 3 ของไทย ทะเลหมอกอลังการและพรรณไม้หายากเฉพาะถิ่น'
    },
    {
        id:'p37',
        name:'ถ้ำเชียงดาว',
        alias:'นักสำรวจถ้ำหินงอกหินย้อย',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.5,
        dist:70.50,
        price:'20-40 บาท',
        zone:'อำเภอ เชียงดาว',
        lat:19.3905, lng:98.9284,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpyOitxsa0uGh4JysnI2pI-ugWrSaMck1bkV3WR-R9uA&s=10',
        desc:'ถ้ำหินปูนขนาดใหญ่ภายในมีหินงอกหินย้อยระยิบระยับและความเชื่อศรัทธาสิ่งศักดิ์สิทธิ์'
    },
    {
        id:'p38',
        name:'บ้านนาเลาใหม่',
        alias:'นักชมวิวดอยหลวงหน้าบ้าน',
        cat:'village',
        coins:95,
        xp:120,
        stars:4.8,
        dist:78.40,
        price:'ฟรี',
        zone:'อำเภอ เชียงดาว',
        lat:19.4121, lng:98.8654,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'หมู่บ้านมูเซอโฮมสเตย์ยอดฮิต มองเห็นดอยหลวงเชียงดาวตั้งตระหง่านอยู่ตรงหน้าอย่างใกล้ชิด'
    },
    {
        id:'p39',
        name:'ระเบียงดาว โฮมสเตย์',
        alias:'นักพักผ่อนมองดาวเคียงดอย',
        cat:'village',
        coins:90,
        xp:110,
        stars:4.7,
        dist:78.80,
        price:'ค่าที่พักตามแพ็กเกจ',
        zone:'อำเภอ เชียงดาว',
        lat:19.4142, lng:98.8682,
        img:'https://images.unsplash.com/photo-1511497584788-876761142191?w=500',
        desc:'ที่พักระเบียงไม้ชื่อดัง สัมผัสอากาศหนาวและดูดาวยามค่ำคืนเคลียดยอดดอยหลวง'
    },
    {
        id:'p40',
        name:'เมืองคอง',
        alias:'นักเดินทางค้นหาดินแดนลับกลางหุบเขา',
        cat:'village',
        coins:100,
        xp:130,
        stars:4.7,
        dist:92.00,
        price:'ฟรี',
        zone:'อำเภอ เชียงดาว',
        lat:19.3812, lng:98.7842,
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500',
        desc:'หุบเขาธรรมชาติเงียบสงบหลังดอยหลวงเชียงดาว เหมาะกับการล่องแพและพักผ่อนสลบโลก'
    },

    // --- อำเภอ ดอยสะเก็ด ---
    {
        id:'p41',
        name:'วัดพระธาตุดอยสะเก็ด',
        alias:'ผู้สักการะพระธาตุบนเนินเขา',
        cat:'temple',
        coins:50,
        xp:60,
        stars:4.5,
        dist:18.50,
        price:'ฟรี',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8712, lng:99.1412,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดเก่าแก่บนยอดเนินเขาสูง มองเห็นวิวทิวทัศน์อำเภอดอยสะเก็ดและอ่างเก็บน้ำ'
    },
    {
        id:'p42',
        name:'น้ำพุร้อนสันกำแพง (พื้นที่คาบเกี่ยว/ดอยสะเก็ด)',
        alias:'นักแช่เท้าผ่อนคลายน้ำแร่ธรรมชาติ',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.5,
        dist:32.00,
        price:'100 บาท',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8254, lng:99.2391,
        img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500',
        desc:'แหล่งน้ำพุร้อนธรรมชาติ มีกิจกรรมต้มไข่และบ่อแช่เท้ารักษาความเมื่อยล้า'
    },
    {
        id:'p43',
        name:'เขื่อนแม่กวงอุดมธารา',
        alias:'นักชมวิวผืนน้ำกว้างใหญ่',
        cat:'natural',
        coins:45,
        xp:55,
        stars:4.3,
        dist:22.10,
        price:'ฟรี',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.9102, lng:99.1584,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'เขื่อนขนาดใหญ่ บรรยากาศร่มรื่น เหมาะกับการนั่งพักผ่อนชมวิวและทานอาหารริมน้ำ'
    },
    {
        id:'p44',
        name:'สะพานแขวนเขื่อนแม่กวง',
        alias:'นักเดินสะพานท้าความสูงชมวิวเขื่อน',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.4,
        dist:24.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.9241, lng:99.1621,
        img:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500',
        desc:'สะพานแขวนเชื่อมต่อหมู่บ้านและจุดชมวิวเหนืออ่างเก็บน้ำเขื่อนแม่กวง'
    },
    {
        id:'p45',
        name:'วัดป่ากองข้าว',
        alias:'ผู้แสวงความสงบในสวนป่าดอยสะเก็ด',
        cat:'temple',
        coins:40,
        xp:50,
        stars:4.3,
        dist:20.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8851, lng:99.1302,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดป่าบรรยากาศเงียบสงบ ร่มรื่นด้วยต้นไม้ใหญ่ เหมาะสำหรับปฏิบัติธรรม'
    },

    // --- อำเภอ แม่แตง ---
    {
        id:'p46',
        name:'ปางช้างแม่แตง',
        alias:'เพื่อนสนิทน้องช้างแสนรู้',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.5,
        dist:45.00,
        price:'ตามแพ็กเกจ',
        zone:'อำเภอ แม่แตง',
        lat:19.1212, lng:98.8912,
        img:'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=500',
        desc:'ปางช้างชื่อดังริมแม่น้ำแม่แตง ชมการแสดงช้าง อาบน้ำช้าง และนั่งแพไม้ไผ่'
    },
    {
        id:'p47',
        name:'วัดบ้านเด่น (วัดเด่นสะหรีศรีเมืองแกน)',
        alias:'ผู้ชื่นชมสถาปัตยกรรมวัดไม้แกะสลักอลังการ',
        cat:'temple',
        coins:70,
        xp:80,
        stars:4.8,
        dist:42.50,
        price:'ฟรี',
        zone:'อำเภอ แม่แตง',
        lat:19.1121, lng:99.0012,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดสวยวิจิตรตระการตาบนเนินเขา โดดเด่นด้วยศิลปะสถาปัตยกรรมล้านนายักษ์และเจดีย์ราย'
    },
    {
        id:'p48',
        name:'ห้วยกุ๊บกั๊บ',
        alias:'นักล่าทะเลหมอกบนดอยไร้ไฟฟ้า',
        cat:'natural',
        coins:110,
        xp:140,
        stars:4.8,
        dist:55.00,
        price:'ค่ารถโฟร์วีลขึ้นดอย',
        zone:'อำเภอ แม่แตง',
        lat:19.2012, lng:98.8121,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'หมู่บ้านบนยอดดอยสูง บรรยากาศเรียบง่าย ไร้ไฟฟ้า ทะเลหมอกหนาแน่นยามเช้า'
    },
    {
        id:'p49',
        name:'สวนสนแม่แตง',
        alias:'ผู้เดินเล่นในสวนสนเกาหลีทิพย์',
        cat:'natural',
        coins:50,
        xp:60,
        stars:4.4,
        dist:48.00,
        price:'ฟรี',
        zone:'อำเภอ แม่แตง',
        lat:19.1512, lng:98.9214,
        img:'https://images.unsplash.com/photo-1511497584788-876761142191?w=500',
        desc:'สวนผลิตเมล็ดพันธุ์ไม้สนสองใบ บรรยากาศโรแมนติกคล้ายต่างประเทศ'
    },
    {
        id:'p50',
        name:'เขื่อนแม่งัดสมบูรณ์ชล',
        alias:'นักพักผ่อนแพนอนกลางน้ำเขื่อน',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.6,
        dist:44.20,
        price:'ค่าเรือ/ค่าแพ',
        zone:'อำเภอ แม่แตง',
        lat:19.1154, lng:99.0412,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'อ่างเก็บน้ำขนาดใหญ่ มีบริการแพที่พักกลางน้ำ อาหารอร่อย และกิจกรรมทางน้ำ'
    },

    // --- อำเภอ แม่ริม ---
    {
        id:'p51',
        name:'ม่อนแจ่ม',
        alias:'นักชมวิวดอกไม้ทะเลหมอกยอดฮิต',
        cat:'natural',
        coins:80,
        xp:95,
        stars:4.6,
        dist:35.50,
        price:'ฟรี (ค่าเข้าสวนดอกไม้แยก)',
        zone:'อำเภอ แม่ริม',
        lat:18.9284, lng:98.8284,
        img:'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=500',
        desc:'จุดชมวิวและสวนดอกไม้เมืองหนาวชื่อดัง วิวภูเขาโอบล้อมและอากาศเย็นสบายตลอดปี'
    },
    {
        id:'p52',
        name:'สวนพฤกษศาสตร์สมเด็จพระนางเจ้าสิริกิติ์',
        alias:'นักเดินสะพานเรือนยอดไม้ Canopy Walkway',
        cat:'natural',
        coins:75,
        xp:90,
        stars:4.8,
        dist:29.10,
        price:'40 บาท',
        zone:'อำเภอ แม่ริม',
        lat:18.8924, lng:98.8681,
        img:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=500',
        desc:'สวนพฤกษศาสตร์ใหญ่ร่มรื่น มีเรือนกระจกกระบองเพชรยักษ์และสะพานชมเรือนยอดไม้ลอยฟ้า'
    },
    {
        id:'p53',
        name:'น้ำตกแม่สา',
        alias:'นักเที่ยวน้ำตก 10 ชั้นยอดนิยม',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.4,
        dist:26.50,
        price:'20 บาท',
        zone:'อำเภอ แม่ริม',
        lat:18.9012, lng:98.8954,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกธรรมชาติขนาดใหญ่มีทั้งหมด 10 ชั้น สายน้ำไหลผ่านร่มไม้เขียวขจี'
    },
    {
        id:'p54',
        name:'โป่งแยง แอดเวนเจอร์ (Jungle Coaster)',
        alias:'นักซิ่งจังเกิ้ลโคสเตอร์สุดมันส์',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.6,
        dist:33.20,
        price:'ค่าเครื่องเล่น',
        zone:'อำเภอ แม่ริม',
        lat:18.9112, lng:98.8412,
        img:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500',
        desc:'สวนสนุกกลางป่าเขา มีเครื่องเล่นซิปไลน์และจังเกิ้ลโคสเตอร์รถรางไม้กลางป่า'
    },
    {
        id:'p55',
        name:'ไร่กุหลาบبعง (สวนดอกไม้ม่อนแจ่ม)',
        alias:'คนรักทุ่งดอกไม้เมืองหนาว',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.5,
        dist:35.80,
        price:'50 บาท',
        zone:'อำเภอ แม่ริม',
        lat:18.9312, lng:98.8312,
        img:'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=500',
        desc:'สวนดอกไม้หลากหลายสีสันบนดอยแม่ริม ถ่ายรูปสวยฉ่ำทุกมุม'
    },

    // --- อำเภอ สะเมิง ---
    {
        id:'p56',
        name:'สวนสตรอว์เบอร์รีสะเมิง',
        alias:'นักชิมสตรอว์เบอร์รีสดจากไร่',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.4,
        dist:45.00,
        price:'ฟรี (ค่าเก็บผลผลิตตามจริง)',
        zone:'อำเภอ สะเมิง',
        lat:18.8512, lng:98.7312,
        img:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500',
        desc:'แหล่งปลูกสตรอว์เบอร์รีที่ใหญ่ที่สุด มีแปลงปลูกให้เก็บสดๆ และผลิตภัณฑ์แปรรูปมากมาย'
    },
    {
        id:'p57',
        name:'จุดชมวิวดอยป่าเมี่ยง',
        alias:'นักชมวิวป่าเขาสะเมิง',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.3,
        dist:42.10,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8812, lng:98.7712,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวบนเส้นทางคดเคี้ยวระหว่างทางไปสะเมิง บรรยากาศธรรมชาติบริสุทธิ์'
    },
    {
        id:'p58',
        name:'วัดพระธาตุดอยนก',
        alias:'ผู้สักการะพระธาตุบนยอดดอยสูงสะเมิง',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.4,
        dist:48.50,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8212, lng:98.6912,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดและจุดชมวิวเงียบสงบ มองเห็นทัศนียภาพอำเภอสะเมิงแบบพาโนรามา'
    },
    {
        id:'p59',
        name:'น้ำตกแม่สาบ',
        alias:'นักท่องน้ำตกธรรมชาติซ่อนเร้น',
        cat:'natural',
        coins:50,
        xp:60,
        stars:4.2,
        dist:38.20,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8912, lng:98.7912,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกขนาดเล็กบรรยากาศร่มรื่น เงียบสงบ เหมาะสำหรับแวะพักผ่อนระหว่างทาง'
    },
    {
        id:'p60',
        name:'ไร่ชาป่าเกี๊ยะ',
        alias:'คนรักชาดอยสะเมิง',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.5,
        dist:50.10,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8312, lng:98.7112,
        img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500',
        desc:'ไร่ชาขั้นบันไดบนเนินเขาสะเมิง จิบชาร้อนๆ พร้อมชมวิวหมอก'
    },

    // --- อำเภอ ฝาง ---
    {
        id:'p61',
        name:'ดอยอ่างขาง (สถานีเกษตรหลวงอ่างขาง)',
        alias:'นักชมดอกพญาเสือโคร่งและพืชสวนหนาว',
        cat:'natural',
        coins:120,
        xp:150,
        stars:4.9,
        dist:155.00,
        price:'50 บาท',
        zone:'อำเภอ ฝาง',
        lat:19.9381, lng:99.0412,
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500',
        desc:'สถานีวิจัยเกษตรที่สูงแห่งแรก แปลงปลูกไม้ผลเมืองหนาว ซากุระเมืองไทย และวิวชายแดนเมียนมา'
    },
    {
        id:'p62',
        name:'จุดชมวิวม่อนสน (ดอยอ่างขาง)',
        alias:'นักกางเต็นท์รับลมหนาวทะเลหมอก',
        cat:'natural',
        coins:90,
        xp:110,
        stars:4.8,
        dist:152.00,
        price:'ค่าบริการกางเต็นท์',
        zone:'อำเภอ ฝาง',
        lat:19.9212, lng:99.0312,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดกางเต็นท์ยอดฮิตบนดอยอ่างขาง วิวทะเลหมอกยามเช้าและสนสองใบเรียงราย'
    },
    {
        id:'p63',
        name:'อุทยานแห่งชาติดอยผ้าห่มปก',
        alias:'นักพิชิตยอดดอยสูงอันดับ 2 ของไทย',
        cat:'natural',
        coins:130,
        xp:160,
        stars:4.8,
        dist:140.00,
        price:'50 บาท',
        zone:'อำเภอ ฝาง',
        lat:20.0612, lng:99.1512,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'ยอดดอยสูงอันดับสองของประเทศ มีบ่อน้ำพุร้อนธรรมชาติและจุดชมวิวทะเลหมอกสุดฟิน'
    },
    {
        id:'p64',
        name:'บ่อน้ำร้อนฝาง (ดอยผ้าห่มปก)',
        alias:'นักแช่น้ำแร่ธรรมชาติพุร้อน',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.6,
        dist:135.00,
        price:'50 บาท',
        zone:'อำเภอ ฝาง',
        lat:19.9812, lng:99.1912,
        img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500',
        desc:'บ่อน้ำพุร้อนธรรมชาติขนาดใหญ่ ไอน้ำพุ่งขึ้นสูง มีบ่อแช่ตัวและต้มไข่'
    },
    {
        id:'p65',
        name:'บ้านนอร์ดอ่างขาง (หมู่บ้านขอบด้ง)',
        alias:'นักท่องเที่ยววิถีวัฒนธรรมชาวเผ่า',
        cat:'village',
        coins:75,
        xp:85,
        stars:4.5,
        dist:156.00,
        price:'ฟรี',
        zone:'อำเภอ ฝาง',
        lat:19.9451, lng:99.0512,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'หมู่บ้านชาวเขาเผ่ามูเซอและลีซอ บนดอยอ่างขาง ชมวิถีชีวิตและงานหัตถกรรมพื้นบ้าน'
    },

    // --- อำเภอ แม่อาย ---
    {
        id:'p66',
        name:'วัดท่าตอน',
        alias:'ผู้สักการะพระเจดีย์แก้วบนยอดเขา',
        cat:'temple',
        coins:70,
        xp:80,
        stars:4.7,
        dist:165.00,
        price:'ฟรี',
        zone:'อำเภอ แม่อาย',
        lat:20.0412, lng:99.3912,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดสวยริมแม่น้ำกก บนภูเขาสูง มีพระเจดีย์แก้วบรรจุพระบรมสารีริกธาตุและวิวแม่น้ำมุมสูง'
    },
    {
        id:'p67',
        name:'ดอยสันกำแพง (แม่อาย)',
        alias:'นักผจญภัยชายแดนเหนือสุด',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.4,
        dist:170.00,
        price:'ฟรี',
        zone:'อำเภอ แม่อาย',
        lat:20.1012, lng:99.3112,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวธรรมชาติบนแนวชายแดนไทย-เมียนมา บรรยากาศป่าเขาสมบูรณ์'
    },
    {
        id:'p68',
        name:'สวนส้มธนาธร (แม่อาย)',
        alias:'นักชิมส้มสายน้ำผึ้งหวานฉ่ำ',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.5,
        dist:160.00,
        price:'ค่าเข้าชมสวน',
        zone:'อำเภอ แม่อาย',
        lat:20.0112, lng:99.3212,
        img:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500',
        desc:'สวนส้มขนาดใหญ่ริมแม่น้ำกก ชมแปลงส้มดกอร่อยและชิมน้ำส้มคั้นสดๆ'
    },
    {
        id:'p69',
        name:'น้ำตกตาดหมอก แม่อาย',
        alias:'ผู้ค้นหาน้ำตกกลางป่าลึก',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.3,
        dist:168.00,
        price:'ฟรี',
        zone:'อำเภอ แม่อาย',
        lat:20.0812, lng:99.3512,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกธรรมชาติกลางป่าดิบชื้นในอำเภอแม่อาย น้ำใสเย็นสดชื่น'
    },
    {
        id:'p70',
        name:'แก่งเกาะผึ้ง',
        alias:'นักล่องเรือชมแก่งแม่น้ำกก',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.2,
        dist:162.00,
        price:'ฟรี',
        zone:'อำเภอ แม่อาย',
        lat:20.0212, lng:99.4112,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'โขดหินและแก่งน้ำกลางแม่น้ำกก จุดพักเรือและชมวิวธรรมชาติริมน้ำ'
    },

    // --- อำเภอ พร้าว ---
    {
        id:'p71',
        name:'วัดดอยแม่ปั๋ง',
        alias:'ผู้รำลึกถึงหลวงปู่มั่น ภูริทัตโต',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.6,
        dist:95.00,
        price:'ฟรี',
        zone:'อำเภอ พร้าว',
        lat:19.3112, lng:99.2112,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดปฏิบัติธรรมสำคัญในอำเภอพร้าว สถานที่จำพรรษาของพระอาจารย์มั่น ภูริทัตโต'
    },
    {
        id:'p72',
        name:'อ่างเก็บน้ำห้วยน้ำบ่อ',
        alias:'นักตกปลาและชมวิวอ่างเก็บน้ำพร้าว',
        cat:'natural',
        coins:45,
        xp:55,
        stars:4.2,
        dist:92.00,
        price:'ฟรี',
        zone:'อำเภอ พร้าว',
        lat:19.3612, lng:99.1912,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'อ่างเก็บน้ำบรรยากาศเงียบสงบ ล้อมรอบด้วยภูเขา เหมาะกับการพักผ่อนหย่อนใจ'
    },
    {
        id:'p73',
        name:'ดอยแม่วะ พร้าว',
        alias:'นักเดินป่าศึกษาธรรมชาติพร้าว',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.4,
        dist:102.00,
        price:'ฟรี',
        zone:'อำเภอ พร้าว',
        lat:19.4112, lng:99.2512,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'ภูเขาสูงในเขตอำเภอพร้าว ป่าไม้อุดมสมบูรณ์และอากาศเย็นสบาย'
    },
    {
        id:'p74',
        name:'น้ำตกบัวตองและน้ำพุเจ็ดสี (พื้นที่คาบเกี่ยว/พร้าว-แม่แตง)',
        alias:'นักเที่ยวน้ำตกหนึบหนับปีนป่ายสนุก',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.8,
        dist:55.00,
        price:'ฟรี',
        zone:'อำเภอ พร้าว',
        lat:19.0712, lng:99.0912,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกหินปูนปะการัง หินไม่ลื่นสามารถเดินปีนป่ายขึ้นน้ำตกได้อย่างมหัศจรรย์'
    },
    {
        id:'p75',
        name:'วัดป่า aranyaวิเวก',
        alias:'ผู้แสวงความสงบวิเวกป่าพร้าว',
        cat: 'temple',
        coins:50,
        xp:60,
        stars:4.5,
        dist:98.00,
        price:'ฟรี',
        zone:'อำเภอ พร้าว',
        lat:19.3412, lng:99.1812,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'สำนักสงฆ์และวัดป่าร่มรื่นกลางธรรมชาติ เหมาะแก่การเจริญสมาธิภาวนา'
    },

    // --- อำเภอ สันป่าตอง ---
    {
        id:'p76',
        name:'เวียงกุมกาม (พื้นที่คาบเกี่ยว/สารภี-สันป่าตอง)',
        alias:'นักประวัติศาสตร์เมืองโบราณใต้ดิน',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.4,
        dist:14.00,
        price:'ฟรี',
        zone:'อำเภอ สันป่าตอง',
        lat:18.7212, lng:98.9712,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'ซากเมืองโบราณยุคหริภุญชัย-มังราย ฝังตัวอยู่ใต้ดิน ค้นพบวัดร้างโบราณหลายแห่ง'
    },
    {
        id:'p77',
        name:'วัดต้นพว๋ง (สันป่าตอง)',
        alias:'ผู้กราบไหว้พระธาตุโบราณสันป่าตอง',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:22.00,
        price:'ฟรี',
        zone:'อำเภอ สันป่าตอง',
        lat:18.6112, lng:98.8812,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดเก่าแก่ที่มีสถาปัตยกรรมล้านนาดั้งเดิมและบรรยากาศชุมชนสงบเงียบ'
    },
    {
        id:'p78',
        name:'กาดวัวลาย (โซนหัตถกรรมเครื่องเงิน)',
        alias:'นักช้อปเครื่องเงินโบราณ',
        cat:'village',
        coins:50,
        xp:60,
        stars:4.5,
        dist:16.00,
        price:'ฟรี',
        zone:'อำเภอ สันป่าตอง',
        lat:18.6512, lng:98.9012,
        img:'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=500',
        desc:'แหล่งหัตถกรรมเครื่องเงินและภูมิปัญญาพื้นบ้านขึ้นชื่อของจังหวัดเชียงใหม่'
    },
    {
        id:'p79',
        name:'ตลาดห้วยทราย สันป่าตอง',
        alias:'นักชิมอาหารพื้นบ้านสันป่าตอง',
        cat:'food',
        coins:35,
        xp:45,
        stars:4.2,
        dist:20.50,
        price:'ฟรี',
        zone:'อำเภอ สันป่าตอง',
        lat:18.6212, lng:98.8912,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'ตลาดท้องถิ่นจับจ่ายใช้สอยสินค้าพื้นบ้านและอาหารพื้นเมืองรสชาติดั้งเดิม'
    },
    {
        id:'p80',
        name:'ทุ่งนาบ้านกาด สันป่าตอง',
        alias:'นักปั่นจักรยานชมทุ่งนาชนบท',
        cat:'natural',
        coins:40,
        xp:50,
        stars:4.3,
        dist:23.00,
        price:'ฟรี',
        zone:'อำเภอ สันป่าตอง',
        lat:18.5912, lng:98.8612,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'เส้นทางปั่นจักรยานชมทุ่งนาเขียวขจีและวิถีชีวิตชาวนาในอำเภอสันป่าตอง'
    },

    // --- อำเภอ สันกำแพง ---
    {
        id:'p81',
        name:'ถนนบ่อสร้าง (หมู่บ้านทำร่ม)',
        alias:'ช่างวาดลายร่มกระดาษสา',
        cat:'village',
        coins:50,
        xp:60,
        stars:4.5,
        dist:13.50,
        price:'ฟรี',
        zone:'อำเภอ สันกำแพง',
        lat:18.7612, lng:99.1112,
        img:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500',
        desc:'หมู่บ้านหัตถกรรมทำร่มกระดาษสาและงานฝีมือพื้นบ้านที่มีชื่อเสียงระดับโลก'
    },
    {
        id:'p82',
        name:'น้ำพุร้อนสันกำแพง',
        alias:'นักแช่น้ำแร่ต้มไข่แลนด์มาร์ก',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.6,
        dist:32.50,
        price:'100 บาท',
        zone:'อำเภอ สันกำแพง',
        lat:18.8254, lng:99.2391,
        img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500',
        desc:'แหล่งน้ำพุร้อนธรรมชาติพุ่งขึ้นสูง มีธารน้ำแร่สำหรับแช่เท้าและลานกางเต็นท์'
    },
    {
        id:'p83',
        name:'ถ้ำผาตั้ง สันกำแพง',
        alias:'นักสำรวจถ้ำหินปูนสันกำแพง',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.3,
        dist:28.00,
        price:'ฟรี',
        zone:'อำเภอ สันกำแพง',
        lat:18.8012, lng:99.2012,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'ถ้ำหินปูนธรรมชาติในเขตอำเภอสันกำแพง หินงอกหินย้อยสวยงาม'
    },
    {
        id:'p84',
        name:'ศูนย์หัตถกรรมผ้าไหมไทยสันกำแพง',
        alias:'นักช้อปผ้าไหมทอมือลวดลายงาม',
        cat:'village',
        coins:45,
        xp:55,
        stars:4.4,
        dist:15.00,
        price:'ฟรี',
        zone:'อำเภอ สันกำแพง',
        lat:18.7512, lng:99.1312,
        img:'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=500',
        desc:'แหล่งจำหน่ายและสาธิตการทอผ้าไหม ผ้าฝ้ายคุณภาพเยี่ยมของสันกำแพง'
    },
    {
        id:'p85',
        name:'สวนน้ำทูปเทร็ค (Tube Trek Water Park)',
        alias:'นักซิ่งสไลเดอร์สวนน้ำสุดมันส์',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.4,
        dist:18.20,
        price:'ค่าเข้าสวนน้ำ',
        zone:'อำเภอ สันกำแพง',
        lat:18.7712, lng:99.0912,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'สวนน้ำธีมาอวกาศขนาดใหญ่ เครื่องเล่นสไลเดอร์และคลื่นเทียมสนุกสนาน'
    },

    // --- อำเภอ สันทราย ---
    {
        id:'p86',
        name:'วัดพระธาตุดอยจอมثอง (สันทราย)',
        alias:'ผู้สักการะพระธาตุสันทราย',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:15.00,
        price:'ฟรี',
        zone:'อำเภอ สันทราย',
        lat:18.9112, lng:99.0112,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดเก่าแก่บนเนินเขาในอำเภอสันทราย บรรยากาศร่มรื่นเงียบสงบ'
    },
    {
        id:'p87',
        name:'ตลาดแม่โจ้',
        alias:'นักชิมสตรีทฟู้ดใกล้มหา’ลัย',
        cat:'food',
        coins:30,
        xp:40,
        stars:4.3,
        dist:14.20,
        price:'ฟรี',
        zone:'อำเภอ สันทราย',
        lat:18.8912, lng:99.0012,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'แหล่งรวมอาหารอร่อยราคานักศึกษาหน้ามหาวิทยาลัยแม่โจ้'
    },
    {
        id:'p88',
        name:'อ่างเก็บน้ำห้วยโจ้',
        alias:'นักปั่นจักรยานรอบอ่างเก็บน้ำสันทราย',
        cat:'natural',
        coins:45,
        xp:55,
        stars:4.4,
        dist:17.50,
        price:'ฟรี',
        zone:'อำเภอ สันทราย',
        lat:18.9312, lng:99.0212,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'อ่างเก็บน้ำในเขตมหาวิทยาลัยแม่โจ้ บรรยากาศลมพัดเย็นสบายเหมาะออกกำลังกาย'
    },
    {
        id:'p89',
        name:'ฟาร์มเกษตรอินทรีย์แม่โจ้',
        alias:'นักท่องเที่ยวเชิงเกษตรอินทรีย์',
        cat:'natural',
        coins:40,
        xp:50,
        stars:4.3,
        dist:16.00,
        price:'ฟรี',
        zone:'อำเภอ สันทราย',
        lat:18.9012, lng:98.9912,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'แหล่งเรียนรู้การทำเกษตรอินทรีย์ แปลงผักและพืชสวนสมบูรณ์'
    },
    {
        id:'p90',
        name:'วัดป่าอิสระธรรม สันทราย',
        alias:'ผู้แสวงธรรมะสันทราย',
        cat:'temple',
        coins:40,
        xp:50,
        stars:4.4,
        dist:19.00,
        price:'ฟรี',
        zone:'อำเภอ สันทราย',
        lat:18.9412, lng:99.0412,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดป่าร่มรื่นเงียบสงบ เหมาะกับการมาปฏิบัติธรรมและพักผ่อนจิตใจ'
    },

    // --- อำเภอ หางดง ---
    {
        id:'p91',
        name:'แกรนด์แคนยอน หางดง',
        alias:'นักโดดน้ำและถ่ายรูปแกรนด์แคนยอนเมืองไทย',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.5,
        dist:12.50,
        price:'100-500 บาท',
        zone:'อำเภอ หางดง',
        lat:18.7012, lng:98.9112,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'แอ่งน้ำสีฟ้ามรกตขนาดใหญ่เกิดจากการขุดดิน หน้าผาดินสูงชันคล้ายแกรนด์แคนยอน'
    },
    {
        id:'p92',
        name:'เชียงใหม่ไนท์ซาฟารี (Chiang Mai Night Safari)',
        alias:'นักส่องสัตว์ยามค่ำคืน',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.6,
        dist:11.00,
        price:'ค่าเข้าชมตามแพ็กเกจ',
        zone:'อำเภอ หางดง',
        lat:18.7412, lng:98.9112,
        img:'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=500',
        desc:'สวนสัตว์เปิดยามค่ำคืน นั่งรถรางชมสัตว์ป่านานาชนิดอย่างใกล้ชิด'
    },
    {
        id:'p93',
        name:'อุทยานหลวงราชพฤกษ์',
        alias:'นักชมสวนพฤกษศาสตร์นานาชาติ',
        cat:'natural',
        coins:70,
        xp:85,
        stars:4.7,
        dist:9.50,
        price:'100 บาท',
        zone:'อำเภอ หางดง',
        lat:18.7454, lng:98.9284,
        img:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=500',
        desc:'สวนพฤกษศาสตร์และหอคำหลวงสถาปัตยกรรมล้านนาอันวิจิตรตระการตา'
    },
    {
        id:'p94',
        name:'วัดต้นเก็ง (วัดอินทราวาส)',
        alias:'ผู้ชื่นชมหอไตรไม้โบราณล้านนา',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.6,
        dist:10.20,
        price:'ฟรี',
        zone:'อำเภอ หางดง',
        lat:18.7112, lng:98.9312,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดเก่าแก่ที่มีหอไตรไม้โบราณอายุกว่าร้อยปี สมบูรณ์ที่สุดแห่งหนึ่งในล้านนา'
    },
    {
        id:'p95',
        name:'บ้านถวาย (หมู่บ้านแกะสลักไม้)',
        alias:'นักช้อปงานไม้แกะสลักฝีมือเยี่ยม',
        cat:'village',
        coins:55,
        xp:65,
        stars:4.5,
        dist:15.00,
        price:'ฟรี',
        zone:'อำเภอ หางดง',
        lat:18.6712, lng:98.9112,
        img:'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=500',
        desc:'หมู่บ้านหัตถกรรมแกะสลักไม้ชื่อดังระดับประเทศ มีสินค้าไม้แกะสลักและของตกแต่งบ้านมากมาย'
    },

    // --- อำเภอ ฮอด ---
    {
        id:'p96',
        name:'อุทยานแห่งชาติออบหลวง',
        alias:'นักผจญภัยหุบผาหน้าผาลึก',
        cat:'natural',
        coins:80,
        xp:95,
        stars:4.6,
        dist:88.00,
        price:'50 บาท',
        zone:'อำเภอ ฮอด',
        lat:18.2312, lng:98.5712,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'หน้าผาหินแกรนิตถูกแม่น้ำแม่แจ่มเซาะผ่านเป็นหุบผาลึก มีสะพานแขวนชมวิวและภาพเขียนโบราณ'
    },
    {
        id:'p97',
        name:'สวนสนบ่อหลวง',
        alias:'นักถ่ายรูปสวนสนบรรยากาศยุโรป',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.7,
        dist:95.00,
        price:'ฟรี',
        zone:'อำเภอ ฮอด',
        lat:18.1512, lng:98.3912,
        img:'https://images.unsplash.com/photo-1511497584788-876761142191?w=500',
        desc:'สวนสนสามใบปลูกเรียงรายสวยงาม บรรยากาศโรแมนติกเหมือนอยู่ต่างประเทศ'
    },
    {
        id:'p98',
        name:'เขื่อนภูมิพล (พื้นที่คาบเกี่ยว ฮอด-ตาก)',
        alias:'นักชมวิวผืนน้ำเขื่อนยักษ์',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.5,
        dist:105.00,
        price:'ฟรี',
        zone:'อำเภอ ฮอด',
        lat:17.2512, lng:99.0312,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'เขื่อนคอนกรีตรูปโค้งขนาดใหญ่ที่สุดในประเทศไทย วิวทะเลสาบเหนือเขื่อนกว้างไกล'
    },
    {
        id:'p99',
        name:'วัดพระธาตุ 4 ดวง (ฮอด)',
        alias:'ผู้สักการะพระธาตุโบราณฮอด',
        cat:'temple',
        coins:50,
        xp:60,
        stars:4.4,
        dist:85.00,
        price:'ฟรี',
        zone:'อำเภอ ฮอด',
        lat:18.2412, lng:98.6112,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดเก่าแก่ในอำเภอฮอด รวบรวมองค์พระธาตุสำคัญโบราณไว้สักการะ'
    },
    {
        id:'p100',
        name:'หุบผาสวรรค์ ฮอด',
        alias:'นักสำรวจธรรมชาติฮอด',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.3,
        dist:90.00,
        price:'ฟรี',
        zone:'อำเภอ ฮอด',
        lat:18.2012, lng:98.5112,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'ธรรมชาติป่าเขาและลำธารใสในเขตอำเภอฮอด เหมาะกับการเดินทางท่องเที่ยวเชิงผจญภัย'
    },

    // --- อำเภอ ดอยเต่า ---
    {
        id:'p101',
        name:'ทะเลสาบดอยเต่า',
        alias:'นักล่องแพรับลมทะเลสาบเหนือเขื่อน',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.3,
        dist:110.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยเต่า',
        lat:17.9112, lng:98.8112,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'ทะเลสาบกว้างขวางเกิดจากเขื่อนภูมิพล มีบริการแพร้านอาหารและชมวิวทิวทัศน์'
    },
    {
        id:'p102',
        name:'วัดดอยเต่า (วัดพระธาตุดอยเต่า)',
        alias:'ผู้สักการะพระธาตุดอยเต่า',
        cat:'temple',
        coins:50,
        xp:60,
        stars:4.4,
        dist:108.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยเต่า',
        lat:17.9312, lng:98.8312,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดบนเนินเขาสูงมองเห็นวิวทะเลสาบดอยเต่าแบบพาโนรามา'
    },
    {
        id:'p103',
        name:'หาดทรายงาม ดอยเต่า',
        alias:'นักพักผ่อนริมหาดน้ำจืดดอยเต่า',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.2,
        dist:115.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยเต่า',
        lat:17.8812, lng:98.7912,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'หาดทรายริมอ่างเก็บน้ำดอยเต่า ช่วงน้ำลดจะโผล่เป็นหาดทรายกว้างให้ลงเล่นน้ำ'
    },
    {
        id:'p104',
        name:'ป่าชุมชนบ้านสบเต่า',
        alias:'นักท่องเที่ยววิถีป่าชุมชนดอยเต่า',
        cat:'village',
        coins:45,
        xp:55,
        stars:4.1,
        dist:112.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยเต่า',
        lat:17.9512, lng:98.8512,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'ชุมชนริมน้ำและผืนป่าธรรมชาติ อนุรักษ์สิ่งแวดล้อมและวิถีชีวิตชาวประมงน้ำจืด'
    },
    {
        id:'p105',
        name:'จุดชมวิวแม่น้ำปิง ดอยเต่า',
        alias:'นักชมวิวแม่น้ำสายสำคัญ',
        cat:'natural',
        coins:50,
        xp:60,
        stars:4.3,
        dist:107.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยเต่า',
        lat:17.9412, lng:98.8012,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'จุดชมวิวสายน้ำปิงไหลผ่านก่อนเข้าสู่ทะเลสาบเหนือเขื่อนภูมิพล'
    },

    // --- อำเภอ อมก๋อย ---
    {
        id:'p106',
        name:'ดอยมงจอง อมก๋อย',
        alias:'นักเดินป่าล่าทุ่งหญ้าทองคำดอยมงจอง',
        cat:'natural',
        coins:140,
        xp:180,
        stars:4.9,
        dist:145.00,
        price:'ค่าไกด์และรถโฟร์วีล',
        zone:'อำเภอ อมก๋อย',
        lat:17.8012, lng:98.3512,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'ยอดดอยยอดฮิตที่มีทุ่งหญ้าสีทองกว้างใหญ่ รูปร่างหน้าผาสิงโตและวิวทะเลหมอกสุดอลังการ'
    },
    {
        id:'p107',
        name:'หมู่บ้านกะเหรี่ยงอมก๋อย',
        alias:'นักท่องเที่ยวสัมผัสวิถีชีวิตดอยลึก',
        cat:'village',
        coins:80,
        xp:95,
        stars:4.4,
        dist:140.00,
        price:'ฟรี',
        zone:'อำเภอ อมก๋อย',
        lat:17.8122, lng:98.4112,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'ชุมชนชาวเขาเผ่าปกาเกอะญอท่ามกลางหุบเขาธรรมชาติอันห่างไกล'
    },
    {
        id:'p108',
        name:'น้ำตกแม่ตื่น อมก๋อย',
        alias:'ผู้ค้นหาน้ำตกกลางป่าอมก๋อย',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.3,
        dist:150.00,
        price:'ฟรี',
        zone:'อำเภอ อมก๋อย',
        lat:17.6512, lng:98.4512,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกธรรมชาติขนาดใหญ่ในลุ่มน้ำแม่ตื่น ป่าเขาสมบูรณ์ดิบชื้น'
    },
    {
        id:'p109',
        name:'อ่างเก็บน้ำห้วยส้ม อมก๋อย',
        alias:'นักชมวิวอ่างเก็บน้ำอมก๋อย',
        cat:'natural',
        coins:50,
        xp:60,
        stars:4.2,
        dist:138.00,
        price:'ฟรี',
        zone:'อำเภอ อมก๋อย',
        lat:17.7912, lng:98.7112,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'แหล่งน้ำธรรมชาติและจุดพักผ่อนในอำเภออมก๋อย'
    },
    {
        id:'p110',
        name:'วัดอมก๋อยกลางเมือง',
        alias:'ผู้สักการะสิ่งศักดิ์สิทธิ์อมก๋อย',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:135.00,
        price:'ฟรี',
        zone:'อำเภอ อมก๋อย',
        lat:17.8012, lng:98.7512,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดศูนย์Iกลางชุมชนอำเภออมก๋อย ศิลปะพื้นถิ่นล้านนาผสมผสาน'
    },

    // --- อำเภอ สารภี ---
    {
        id:'p111',
        name:'ถนนต้นยางนา สารภี',
        alias:'นักปั่นจักรยานใต้ร่มเงายางนาโบราณ',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.6,
        dist:12.00,
        price:'ฟรี',
        zone:'อำเภอ สารภี',
        lat:18.7212, lng:99.0112,
        img:'https://images.unsplash.com/photo-1511497584788-876761142191?w=500',
        desc:'ถนนสายประวัติศาสตร์เชียงใหม่-ลำพูน สองข้างทางเรียงรายด้วยต้นยางนาอายุหลายร้อยปี'
    },
    {
        id:'p112',
        name:'วัดป่าแดด สารภี',
        alias:'ผู้กราบไหว้พระธาตุและภาพจิตรกรรม',
        cat:'temple',
        coins:50,
        xp:60,
        stars:4.5,
        dist:10.50,
        price:'ฟรี',
        zone:'อำเภอ สารภี',
        lat:18.7312, lng:98.9912,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดเก่าแก่ที่มีจิตรกรรมฝาผนังและสถาปัตยกรรมล้านนาอันทรงคุณค่า'
    },
    {
        id:'p113',
        name:'เวียงกุมกาม (โซนสารภี)',
        alias:'นักสำรวจเวียงโบราณ',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.4,
        dist:11.00,
        price:'ฟรี',
        zone:'อำเภอ สารภี',
        lat:18.7354, lng:98.9854,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'เขตเมืองโบราณใต้ดินฝั่งอำเภอสารภี มีซากวัดร้างและโบราณวัตถุ'
    },
    {
        id:'p114',
        name:'สวนผลไม้ป้าปิ่น สารภี',
        alias:'นักชิมผลไม้สดจากสวนสารภี',
        cat:'natural',
        coins:45,
        xp:55,
        stars:4.3,
        dist:14.00,
        price:'ตามผลผลิต',
        zone:'อำเภอ สารภี',
        lat:18.7012, lng:99.0312,
        img:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500',
        desc:'สวนผลไม้ท้องถิ่น เช่น ลำไย และมะม่วง ให้เที่ยวชมและชิมสดๆ'
    },
    {
        id:'p115',
        name:'ตลาดสดสารภี',
        alias:'นักชิมของกินพื้นบ้านสารภี',
        cat:'food',
        coins:35,
        xp:45,
        stars:4.2,
        dist:13.00,
        price:'ฟรี',
        zone:'อำเภอ สารภี',
        lat:18.7112, lng:99.0112,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'ตลาดท้องถิ่นจับจ่ายอาหารพื้นเมืองและสินค้าเกษตรกรรม'
    },

    // --- อำเภอ เวียงแหง ---
    {
        id:'p116',
        name:'พระธาตุเวียงแหง',
        alias:'ผู้สักการะพระธาตุแสนkมื่น',
        cat:'temple',
        coins:70,
        xp:80,
        stars:4.5,
        dist:130.00,
        price:'ฟรี',
        zone:'อำเภอ เวียงแหง',
        lat:19.5512, lng:98.6112,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'พระธาตุโบราณศักดิ์สิทธิ์คู่เมืองเวียงแหง ชายแดนไทย-เมียนมา'
    },
    {
        id:'p117',
        name:'จุดชมวิวดอยเปียงหลวง เวียงแหง',
        alias:'นักล่าทะเลหมอกชายแดนเวียงแหง',
        cat:'natural',
        coins:90,
        xp:110,
        stars:4.7,
        dist:135.00,
        price:'ฟรี',
        zone:'อำเภอ เวียงแหง',
        lat:19.6112, lng:98.5512,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวทะเลหมอกสุดขอบประเทศ วิวภูเขาซับซ้อนและวัฒนธรรมไทยใหญ่'
    },
    {
        id:'p118',
        name:'ถ้ำลอดเวียงแหง',
        alias:'นักสำรวจถ้ำลึกเวียงแหง',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.4,
        dist:128.00,
        price:'ค่าไกด์ท้องถิ่น',
        zone:'อำเภอ เวียงแหง',
        lat:19.5212, lng:98.6512,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'ถ้ำหินปูนธรรมชาติในอำเภอเวียงแหง ภายในมีหินงอกหินย้อยตระการตา'
    },
    {
        id:'p119',
        name:'หมู่บ้านไต (ไทยใหญ่) เวียงแหง',
        alias:'นักท่องเที่ยววัฒนธรรมไทใหญ่ดั้งเดิม',
        cat:'village',
        coins:65,
        xp:75,
        stars:4.6,
        dist:132.00,
        price:'ฟรี',
        zone:'อำเภอ เวียงแหง',
        lat:19.5712, lng:98.5912,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'ชุมชนชาวไทยใหญ่ สัมผัสสถาปัตยกรรมบ้านเรือน อาหาร และประเพณีพื้นบ้าน'
    },
    {
        id:'p120',
        name:'อ่างเก็บน้ำเวียงแหง',
        alias:'นักพักผ่อนริมอ่างเก็บน้ำเวียงแหง',
        cat:'natural',
        coins:50,
        xp:60,
        stars:4.2,
        dist:125.00,
        price:'ฟรี',
        zone:'อำเภอ เวียงแหง',
        lat:19.5312, lng:98.6812,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'แหล่งน้ำธรรมชาติและจุดพักผ่อนหย่อนใจโอบล้อมด้วยขุนเขา'
    },

    // --- อำเภอ ไชยปราการ ---
    {
        id:'p121',
        name:'วัดถ้ำตับเต่า ไชยปราการ',
        alias:'ผู้สำรวจถ้ำและกราบพระพุทธรูปในถ้ำ',
        cat:'temple',
        coins:65,
        xp:75,
        stars:4.5,
        dist:120.00,
        price:'ฟรี',
        zone:'อำเภอ ไชยปราการ',
        lat:19.7512, lng:99.0112,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'วัดและถ้ำหินปูนศักดิ์สิทธิ์ ประดิษฐานพระพุทธรูปทองคำและพระนอนองค์ใหญ่ภายในถ้ำ'
    },
    {
        id:'p122',
        name:'ดอยผาตั้ง ไชยปราการ',
        alias:'นักพิชิตดอยผาตั้งชมวิวทะเลหมอก',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.6,
        dist:125.00,
        price:'ฟรี',
        zone:'อำเภอ ไชยปราการ',
        lat:19.8112, lng:98.9512,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวพระอาทิตย์ขึ้นและทะเลหมอกบนแนวชายแดนอำเภอไชยปราการ'
    },
    {
        id:'p123',
        name:'สวนส้มไชยปราการ',
        alias:'นักชิมส้มสดจากไร่ไชยปราการ',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.4,
        dist:118.00,
        price:'ค่าเข้าชมสวน',
        zone:'อำเภอ ไชยปราการ',
        lat:19.7212, lng:99.0512,
        img:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500',
        desc:'แหล่งปลูกส้มพันธุ์ดี ผลผลิตดกหวานฉ่ำเปิดให้นักท่องเที่ยวเข้าชม'
    },
    {
        id:'p124',
        name:'น้ำตกป่าคา ไชยปราการ',
        alias:'นักท่องน้ำตกใสไชยปราการ',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.3,
        dist:122.00,
        price:'ฟรี',
        zone:'อำเภอ ไชยปราการ',
        lat:19.7812, lng:98.9812,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกธรรมชาติกลางป่าร่มรื่น น้ำใสเย็นสบายในเขตอำเภอไชยปราการ'
    },
    {
        id:'p125',
        name:'หมู่บ้านชนเผ่าไชยปราการ',
        alias:'นักศึกษาวัฒนธรรมชนเผ่าไชยปราการ',
        cat:'village',
        coins:60,
        xp:70,
        stars:4.4,
        dist:126.00,
        price:'ฟรี',
        zone:'อำเภอ ไชยปราการ',
        lat:19.7612, lng:98.9312,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'ชุมชนชาวเขาหลากหลายเผ่าที่อาศัยอยู่ร่วมกันอย่างกลมกลืน'
    },

    // --- อำเภอ แม่วาง ---
    {
        id:'p126',
        name:'ปางช้างไฉไลออร์คิด แม่วาง',
        alias:'นักกอดช้างริมธารน้ำแม่วาง',
        cat:'natural',
        coins:80,
        xp:95,
        stars:4.7,
        dist:42.00,
        price:'ตามแพ็กเกจ',
        zone:'อำเภอ แม่วาง',
        lat:18.6112, lng:98.7112,
        img:'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=500',
        desc:'ปางช้างริมแม่น้ำแม่วาง กิจกรรมอาบน้ำช้าง ถ่ายรูปกับน้องช้าง และพักบ้านพักธรรมชาติ'
    },
    {
        id:'p127',
        name:'ล่องแพไม้ไผ่ แม่วาง',
        alias:'นักล่องแพไม้ไผ่ท้าสายน้ำแม่วาง',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.5,
        dist:44.00,
        price:'200-500 บาท',
        zone:'อำเภอ แม่วาง',
        lat:18.5912, lng:98.7312,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'กิจกรรมล่องแพไม้ไผ่ไปตามลำน้ำแม่วาง ชมธรรมชาติสองฝั่งลำธาร'
    },
    {
        id:'p128',
        name:'ผาช่อ อุทยานแห่งชาติแม่วาง',
        alias:'นักสำรวจแกรนด์แคนยอนเมืองไทยผาช่อ',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.6,
        dist:45.50,
        price:'20 บาท',
        zone:'อำเภอ แม่วาง',
        lat:18.5112, lng:98.7512,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'หน้าผาดินตะกอนสูงชันแปลกตา เกิดจากการเปลี่ยนเส้นทางเดินของแม่น้ำปิงในอดีต'
    },
    {
        id:'p129',
        name:'น้ำตกแม่วาง',
        alias:'นักเที่ยวน้ำตกชิลๆ แม่วาง',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.3,
        dist:40.00,
        price:'ฟรี',
        zone:'อำเภอ แม่วาง',
        lat:18.6312, lng:98.6912,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกขนาดกลางบรรยากาศร่มรื่น เหมาะสำหรับการนั่งปิกนิกและเล่นน้ำ'
    },
    {
        id:'p130',
        name:'วัดหลวงแม่วาง',
        alias:'ผู้สักการะวัดสำคัญแม่วาง',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.4,
        dist:39.00,
        price:'ฟรี',
        zone:'อำเภอ แม่วาง',
        lat:18.6412, lng:98.7012,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดศูนย์กลางชุมชนแม่วาง สถาปัตยกรรมล้านนาสวยงาม'
    },

    // --- อำเภอ แม่ออน ---
    {
        id:'p131',
        name:'หมู่บ้านแม่กำปอง',
        alias:'นักพักผ่อนโฮมสเตย์กลางป่าเขียวขจี',
        cat:'village',
        coins:110,
        xp:140,
        stars:4.8,
        dist:50.00,
        price:'ฟรี',
        zone:'อำเภอ แม่ออน',
        lat:18.8682, lng:99.2782,
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500',
        desc:'หมู่บ้านท่องเที่ยวเชิงนิเวศยอดฮิตในหุบเขา อากาศเย็นสบายตลอดปี ลำธารไหลผ่านกลางหมู่บ้าน'
    },
    {
        id:'p132',
        name:'น้ำตกแม่กำปอง',
        alias:'นักชื่นชมสายน้ำกลางป่าแม่กำปอง',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.6,
        dist:51.50,
        price:'ฟรี',
        zone:'อำเภอ แม่ออน',
        lat:18.8712, lng:99.2854,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกธรรมชาติหลายชั้นไหลผ่านผืนป่าดิบชื้น ใกล้หมู่บ้านแม่กำปอง'
    },
    {
        id:'p133',
        name:'Teddu Coffee (แม่กำปอง)',
        alias:'นักจิบกาแฟบนสะพานแขวนกลางป่า',
        cat:'food',
        coins:70,
        xp:80,
        stars:4.7,
        dist:51.20,
        price:'100-200 บาท',
        zone:'อำเภอ แม่ออน',
        lat:18.8702, lng:99.2812,
        img:'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=500',
        desc:'คาเฟ่ชื่อดังกลางป่าใหญ่ ใกล้ลำธาร มีสะพานแขวนยอดฮิตให้ถ่ายรูปคู่กับน้ำตก'
    },
    {
        id:'p134',
        name:'วัดแม่กำปอง (วัดคันธาพฤกษาราม)',
        alias:'ผู้กราบไหว้โบสถ์กลางน้ำแม่กำปอง',
        cat:'temple',
        coins:60,
        xp:70,
        stars:4.6,
        dist:50.50,
        price:'ฟรี',
        zone:'อำเภอ แม่ออน',
        lat:18.8692, lng:99.2792,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดไม้โบราณมีอุโบสถกลางน้ำและสถาปัตยกรรมล้านนาอันเป็นเอกลักษณ์'
    },
    {
        id:'p135',
        name:'กิ่วฝิ่น (จุดชมวิวดอยแม่กำปอง)',
        alias:'นักล่าทะเลหมอกสองแผ่นดิน',
        cat:'natural',
        coins:100,
        xp:130,
        stars:4.8,
        dist:55.00,
        price:'ค่ารถบริการขึ้นจุดชมวิว',
        zone:'อำเภอ แม่ออน',
        lat:18.8812, lng:99.3112,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวบนยอดดอยเขตรอยต่อเชียงใหม่-ลำปาง ทะเลหมอกกว้างไกลสุดสายตา'
    },

    // --- อำเภอ ดอยหล่อ ---
    {
        id:'p136',
        name:'ผาช่อ (ฝั่งดอยหล่อ)',
        alias:'นักสำรวจประติมากรรมดินธรรมชาติ',
        cat:'natural',
        coins:80,
        xp:95,
        stars:4.6,
        dist:45.00,
        price:'20 บาท',
        zone:'อำเภอ ดอยหล่อ',
        lat:18.4912, lng:98.7612,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'เสาดินและหน้าผาดินสูงตระหง่านเกิดจากการกัดเซาะของธรรมชาติ'
    },
    {
        id:'p137',
        name:'วัดพระธาตุดอยน้อย ดอยหล่อ',
        alias:'ผู้สักการะพระธาตุดอยน้อยริมปิง',
        cat:'temple',
        coins:55,
        xp:65,
        stars:4.5,
        dist:42.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยหล่อ',
        lat:18.4212, lng:98.7112,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดโบราณบนยอดดอยเตี้ยๆ ริมแม่น้ำปิง สร้างขึ้นตั้งแต่สมัยพระนางจามเทวี'
    },
    {
        id:'p138',
        name:'อ่างเก็บน้ำห้วยสะทก ดอยหล่อ',
        alias:'นักพักผ่อนริมน้ำดอยหล่อ',
        cat:'natural',
        coins:45,
        xp:55,
        stars:4.2,
        dist:48.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยหล่อ',
        lat:18.4512, lng:98.7912,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'แหล่งน้ำธรรมชาติและจุดพักผ่อนหย่อนใจในอำเภอดอยหล่อ'
    },
    {
        id:'p139',
        name:'ตลาดสดดอยหล่อ',
        alias:'นักชิมอาหารพื้นบ้านดอยหล่อ',
        cat:'food',
        coins:35,
        xp:45,
        stars:4.1,
        dist:40.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยหล่อ',
        lat:18.4312, lng:98.6912,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'ตลาดท้องถิ่นจับจ่ายสินค้าเกษตรและอาหารพื้นเมือง'
    },
    {
        id:'p140',
        name:'สวนผลไม้ดอยหล่อ',
        alias:'นักชิมลำไยและผลไม้ดอยหล่อ',
        cat:'natural',
        coins:45,
        xp:55,
        stars:4.3,
        dist:44.00,
        price:'ตามฤดูกาล',
        zone:'อำเภอ ดอยหล่อ',
        lat:18.4712, lng:98.7312,
        img:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500',
        desc:'สวนผลไม้ขึ้นชื่อ โดยเฉพาะลำไยคุณภาพดีของอำเภอดอยหล่อ'
    },

    // --- อำเภอ กัลยาณิวัฒนา ---
    {
        id:'p141',
        name:'บ้านแจ่มหลวง กัลยาณิวัฒนา',
        alias:'นักท่องเที่ยววิถีชุมชนบนดอยสูง',
        cat:'village',
        coins:90,
        xp:110,
        stars:4.7,
        dist:115.00,
        price:'ฟรี',
        zone:'อำเภอ กัลยาณิวัฒนา',
        lat:19.0112, lng:98.1512,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'หมู่บ้านกลางหุบเขาในอำเภอใหม่ล่าสุดของเชียงใหม่ วัฒนธรรมและธรรมชาติบริสุทธิ์'
    },
    {
        id:'p142',
        name:'โครงการพัฒนาพื้นที่สูงตามพระราชดำริบ้านอมลอง',
        alias:'นักศึกษาเกษตรที่สูงกัลยาณิวัฒนา',
        cat:'natural',
        coins:80,
        xp:95,
        stars:4.6,
        dist:120.00,
        price:'ฟรี',
        zone:'อำเภอ กัลยาณิวัฒนา',
        lat:19.0512, lng:98.1112,
        img:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=500',
        desc:'ศูนย์เรียนรู้เกษตรที่สูง แปลงปลูกพืชผักเมืองหนาวและดอกไม้สวยงาม'
    },
    {
        id:'p143',
        name:'วัดจันทร์ (ศูนย์การเรียนรู้ป่าชุมชนวัดจันทร์)',
        alias:'ผู้กราบไหว้พระธาตุวัดจันทร์',
        cat:'temple',
        coins:70,
        xp:80,
        stars:4.5,
        dist:112.00,
        price:'ฟรี',
        zone:'อำเภอ กัลยาณิวัฒนา',
        lat:19.0212, lng:98.1812,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดศูนย์กลางชุมชนตำบลวัดจันทร์ สถาปัตยกรรมไม้สมบูรณ์ท่ามกลางทิวสน'
    },
    {
        id:'p144',
        name:'ป่าสนวัดจันทร์ (องค์การอุตสาหกรรมป่าไม้)',
        alias:'นักพักผ่อนแคมป์ปิ้งในป่าสนใหญ่',
        cat:'natural',
        coins:95,
        xp:120,
        stars:4.8,
        dist:113.00,
        price:'ค่าบริการกางเต็นท์',
        zone:'อำเภอ กัลยาณิวัฒนา',
        lat:19.0312, lng:98.1912,
        img:'https://images.unsplash.com/photo-1511497584788-876761142191?w=500',
        desc:'ป่าสนธรรมชาติผืนใหญ่ที่สุดในประเทศไทย บรรยากาศโรแมนติก ลานกางเต็นท์ริมน้ำ'
    },
    {
        id:'p145',
        name:'จุดชมวิวดอยก่าม กัลยาณิวัฒนา',
        alias:'นักล่าทะเลหมอกกัลยาณิวัฒนา',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.6,
        dist:118.00,
        price:'ฟรี',
        zone:'อำเภอ กัลยาณิวัฒนา',
        lat:19.0812, lng:98.0812,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวบนยอดดอยสูง มองเห็นทัศนียภาพป่าเขาสลับซับซ้อนและทะเลหมอกยามเช้า'
    },

    // --- เพิ่มสถานที่ท่องเที่ยวเพิ่มเติมให้ครบ 200 ที่ (กระจายตามอำเภอต่างๆ) ---
    {
        id:'p146',
        name:'วัดพระธาตุดอยคำ',
        alias:'ผู้ขอพรหลวงพ่อทันใจชื่อดัง',
        cat:'temple',
        coins:75,
        xp:85,
        stars:4.8,
        dist:8.50,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7354, lng:98.9241,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดศักดิ์สิทธิ์บนยอดเขา 1 ในแลนด์มาร์กที่คนนิยมมาขอพรเรื่องโชคลาภกับหลวงพ่อทันใจ'
    },
    {
        id:'p147',
        name:'พิพิธภัณฑ์ศิลปะร่วมสมัย MOCA Chiang Mai',
        alias:'คนรักงานศิลปะร่วมสมัย',
        cat:'village',
        coins:60,
        xp:70,
        stars:4.6,
        dist:2.10,
        price:'ตามประกาศหอศิลป์',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7912, lng:98.9812,
        img:'https://images.unsplash.com/photo-1566127444979-b3d2b65463d7?w=500',
        desc:'แหล่งจัดแสดงผลงานศิลปะร่วมสมัยของศิลปินไทยและต่างชาติใจกลางเมือง'
    },
    {
        id:'p148',
        name:'กาดนัดหน้ามอ (มช.)',
        alias:'นักช้อปแฟชั่นและสตรีทฟู้ดนักศึกษา',
        cat:'food',
        coins:35,
        xp:45,
        stars:4.4,
        dist:3.50,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.8012, lng:98.9554,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'ตลาดนัดสุดคึกคักหน้ามหาวิทยาลัยเชียงใหม่ เสื้อผ้าแฟชั่นและของกินอร่อยราคาประหยัด'
    },
    {
        id:'p149',
        name:'ตลาดจริงใจ (Jing Jai Market)',
        alias:'นักช้อปสินค้าออร์แกนิกและงานคราฟต์',
        cat:'village',
        coins:50,
        xp:60,
        stars:4.7,
        dist:2.80,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.8072, lng:98.9872,
        img:'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=500',
        desc:'ตลาดนัดสุดสัปดาห์จำหน่ายสินค้าเกษตรอินทรีย์ งานแฮนด์เมด และกาแฟดีไซน์เก๋'
    },
    {
        id:'p150',
        name:'วัดศรีสุพรรณ (อุโบสถเงิน)',
        alias:'ผู้ชมอุโบสถเงินร้อยล้าน',
        cat:'temple',
        coins:65,
        xp:75,
        stars:4.6,
        dist:2.20,
        price:'50 บาท',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7754, lng:98.9854,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดที่มีพระอุโบสถเงินบริสุทธิ์และงานหัตถกรรมเครื่องเงินตอกลายวิจิตรตระการตา'
    },
    {
        id:'p151',
        name:'ศูนย์วัฒนธรรมเชียงใหม่',
        alias:'นักชมการแสดงขันโตกและวัฒนธรรมล้านนา',
        cat:'village',
        coins:55,
        xp:65,
        stars:4.3,
        dist:2.50,
        price:'ค่าเข้าชมการแสดง',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7712, lng:98.9812,
        img:'https://images.unsplash.com/photo-1566127444979-b3d2b65463d7?w=500',
        desc:'สถานที่จัดเลี้ยงอาหารขันโตกพร้อมชมการแสดงฟ้อนรำพื้นเมืองล้านนา'
    },
    {
        id:'p152',
        name:'สวนสุขภาพบวกหาด',
        alias:'นักวิ่งออกกำลังกายริมคูเมือง',
        cat:'natural',
        coins:30,
        xp:40,
        stars:4.5,
        dist:1.50,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7782, lng:98.9812,
        img:'https://images.unsplash.com/photo-1598971871298-3c5d98bc67d4?w=500',
        desc:'สวนสาธารณะยอดฮิตมุมคูเมืองด้านใต้ ร่มรื่นด้วยต้นไม้ใหญ่ เหมาะกับการออกกำลังกาย'
    },
    {
        id:'p153',
        name:'ประตูท่าแพ',
        alias:'นักถ่ายรูปคู่ฝูงนกพิราบประตูเมือง',
        cat:'village',
        coins:40,
        xp:50,
        stars:4.6,
        dist:1.20,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7885, lng:98.9912,
        img:'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=500',
        desc:'ประตูเมืองโบราณแลนด์มาร์กสำคัญใจกลางเมืองเชียงใหม่ ลานกิจกรรมยอดนิยม'
    },
    {
        id:'p154',
        name:'วัดพันเตา',
        alias:'ผู้ชื่นชมพระวิหารไม้สักทองจำหลัก',
        cat:'temple',
        coins:50,
        xp:60,
        stars:4.7,
        dist:0.90,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7881, lng:98.9862,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดเก่าแก่ใจกลางเมือง โดดเด่นด้วยพระวิหารไม้สักทองแกะสลักลวดลายงดงาม'
    },
    {
        id:'p155',
        name:'วัดบูรพาราม เชียงใหม่',
        alias:'ผู้สักการะวัดโบราณในเมือง',
        cat:'temple',
        coins:40,
        xp:50,
        stars:4.3,
        dist:1.80,
        price:'ฟรี',
        zone:'อำเภอเมือง เชียงใหม่',
        lat:18.7954, lng:98.9912,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดสงบเงียบในเขตตัวเมืองเชียงใหม่ สถาปัตยกรรมดั้งเดิม'
    },
    {
        id:'p156',
        name:'น้ำตกสิริภูมิ ดอยอินทนนท์',
        alias:'นักชื่นชมน้ำตกคู่แฝดดอยอินทนนท์',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.6,
        dist:52.00,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.5478, lng:98.5112,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกคู่แฝดไหลลงมาจากหน้าผาสูงชันในเขตอุทยานแห่งชาติดอยอินทนนท์'
    },
    {
        id:'p157',
        name:'สถานีเกษตรหลวงอินทนนท์',
        alias:'นักชมแปลงวิจัยพืชผักเมืองหนาว',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.5,
        dist:53.50,
        price:'20 บาท',
        zone:'อำเภอ จอมทอง',
        lat:18.5312, lng:98.5112,
        img:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=500',
        desc:'ศูนย์วิจัยพืชสวน ดอกไม้เมืองหนาว และแปลงปลูกเฟิร์น'
    },
    {
        id:'p158',
        name:'น้ำตกแม่ปาน จอมทอง',
        alias:'นักผจญภัยน้ำตกสูงตระหง่านแม่ปาน',
        cat:'natural',
        coins:75,
        xp:85,
        stars:4.6,
        dist:60.00,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.5112, lng:98.4912,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกขนาดใหญ่ซ่อนตัวอยู่ใกล้หมู่บ้านป่าบงเปียง ความสูงกว่า 100 เมตร'
    },
    {
        id:'p159',
        name:'หมู่บ้านแม่ปาน จอมทอง',
        alias:'นักท่องเที่ยววิถีชีวิตขุนเขาจอมทอง',
        cat:'village',
        coins:70,
        xp:80,
        stars:4.4,
        dist:59.00,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.5212, lng:98.5012,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'หมู่บ้านชาวเขาโปกะญอท่ามกลางหุบเขาและแปลงนาขั้นบันได'
    },
    {
        id:'p160',
        name:'วัดทุ่งต้อม จอมทอง',
        alias:'ผู้สักการะวัดโบราณจอมทอง',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:34.00,
        price:'ฟรี',
        zone:'อำเภอ จอมทอง',
        lat:18.4212, lng:98.6512,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดชุมชนเก่าแก่ในอำเภอจอมทอง สถาปัตยกรรมล้านนาเรียบง่าย'
    },
    {
        id:'p161',
        name:'ถ้ำเชียงดาว (ถ้ำแก้ว)',
        alias:'นักสำรวจถ้ำประดับไฟวิบวับ',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.6,
        dist:71.00,
        price:'50-100 บาท',
        zone:'อำเภอ เชียงดาว',
        lat:19.3921, lng:98.9291,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'โถงถ้ำภายในถ้ำเชียงดาวที่ต้องใช้ตะเกียงนำทาง หินงอกหินย้อยระยิบระยับสวยงาม'
    },
    {
        id:'p162',
        name:'น้ำตกศรีสังวาลย์ เชียงดาว',
        alias:'นักเที่ยวน้ำตกหินปูนชั้นสวยเชียงดาว',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.4,
        dist:75.00,
        price:'ฟรี',
        zone:'อำเภอ เชียงดาว',
        lat:19.3112, lng:98.9112,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกหินปูนชั้นลดหลั่นสวยงามในเขตอุทยานแห่งชาติผาแดง'
    },
    {
        id:'p163',
        name:'ดอยปู่หมื่น เชียงดาว',
        alias:'นักจิบชาออร์แกนิกบนดอยสูง',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.5,
        dist:82.00,
        price:'ฟรี',
        zone:'อำเภอ เชียงดาว',
        lat:19.4512, lng:98.8112,
        img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500',
        desc:'หมู่บ้านและแปลงปลูกชาอัสสัมโบราณบนดอยสูง สัมผัสวิถีชีวิตชาวลาหู่'
    },
    {
        id:'p164',
        name:'วัดถ้ำผาปล่อง เชียงดาว',
        alias:'ผู้เดินบันไดขึ้นวัดป่าปฏิบัติธรรม',
        cat:'temple',
        coins:75,
        xp:85,
        stars:4.8,
        dist:72.00,
        price:'ฟรี',
        zone:'อำเภอ เชียงดาว',
        lat:19.3954, lng:98.9112,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดป่าบนยอดเขา เดินขึ้นบันไดนาค 500 ขั้น สัมผัสความสงบและร่มเงาป่าเขา'
    },
    {
        id:'p165',
        name:'บ้านแม่แมะ เชียงดาว',
        alias:'นักพักโฮมสเตย์ริมลำธารป่าใหญ่',
        cat:'village',
        coins:85,
        xp:100,
        stars:4.7,
        dist:68.00,
        price:'ฟรี',
        zone:'อำเภอ เชียงดาว',
        lat:19.2512, lng:98.9112,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'หมู่บ้านโฮมสเตย์กลางป่า ลำธารไหลผ่าน บรรยากาศเงียบสงบเหมาะแก่การพักผ่อน'
    },
    {
        id:'p166',
        name:'น้ำพุร้อนโป่งกุ่ม ดอยสะเก็ด',
        alias:'นักแช่น้ำแร่ธรรมชาติผ่อนคลายดอยสะเก็ด',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.4,
        dist:35.00,
        price:'50 บาท',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8912, lng:99.2512,
        img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500',
        desc:'บ่อน้ำพุร้อนธรรมชาติขนาดเล็ก บรรยากาศเป็นกันเองและเงียบสงบกว่า'
    },
    {
        id:'p167',
        name:'วัดป่าลาน ดอยสะเก็ด',
        alias:'ผู้แสวงธรรมะป่าดอยสะเก็ด',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:21.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8612, lng:99.1512,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดป่าร่มรื่นเงียบสงบ เหมาะสำหรับผู้ต้องการมาปฏิบัติธรรม'
    },
    {
        id:'p168',
        name:'อ่างเก็บน้ำแม่กวงน้อย ดอยสะเก็ด',
        alias:'นักตกปลาชมวิวอ่างเก็บน้ำดอยสะเก็ด',
        cat:'natural',
        coins:40,
        xp:50,
        stars:4.2,
        dist:25.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8912, lng:99.1812,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'อ่างเก็บน้ำขนาดเล็กบรรยากาศเงียบสงบ ล้อมรอบด้วยธรรมชาติ'
    },
    {
        id:'p169',
        name:'ตลาดสดดอยสะเก็ด',
        alias:'นักชิมอาหารพื้นบ้านดอยสะเก็ด',
        cat:'food',
        coins:35,
        xp:45,
        stars:4.2,
        dist:19.00,
        price:'ฟรี',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8712, lng:99.1312,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'ตลาดท้องถิ่นจับจ่ายสินค้าพื้นเมืองและอาหารเหนือรสชาติดั้งเดิม'
    },
    {
        id:'p170',
        name:'สวนพฤกษศาสตร์ทวีชล ดอยสะเก็ด',
        alias:'นักชมสวนพฤกษศาสตร์และสัตว์ปีก',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.3,
        dist:16.50,
        price:'50 บาท',
        zone:'อำเภอ ดอยสะเก็ด',
        lat:18.8212, lng:99.0912,
        img:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=500',
        desc:'สวนพฤกษศาสตร์กว้างขวาง มีสวนสัตว์ปีก หุ่นไดโนเสาร์ และเรือนไม้ล้านนา'
    },
    {
        id:'p171',
        name:'ปางช้างแม่ตะมาน แม่แตง',
        alias:'นักท่องปางช้างริมแม่น้ำแม่แตง',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.5,
        dist:46.00,
        price:'ตามแพ็กเกจ',
        zone:'อำเภอ แม่แตง',
        lat:19.1312, lng:98.8812,
        img:'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=500',
        desc:'ปางช้างริมแม่น้ำแม่แตง กิจกรรมขี่ช้าง ล่องแพ และนั่งเกวียน'
    },
    {
        id:'p172',
        name:'วัดป่าดาราภิรมย์ (พื้นที่คาบเกี่ยว/แม่ริม-แม่แตง)',
        alias:'ผู้สักการะพระอารามหลวงป่าแม่แตง',
        cat:'temple',
        coins:60,
        xp:70,
        stars:4.7,
        dist:25.00,
        price:'ฟรี',
        zone:'อำเภอ แม่แตง',
        lat:18.9312, lng:98.9112,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดพระอารามหลวง บรรยากาศร่มรื่น สถาปัตยกรรมล้านนาโบราณงดงาม'
    },
    {
        id:'p173',
        name:'แก่งกื๊ด แม่แตง',
        alias:'นักล่องแก่งเรือยางสุดระทึกแม่แตง',
        cat:'natural',
        coins:90,
        xp:110,
        stars:4.7,
        dist:52.00,
        price:'ค่าบริการล่องแก่ง',
        zone:'อำเภอ แม่แตง',
        lat:19.1812, lng:98.7512,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'แหล่งล่องแก่งเรือยางระดับท็อปของประเทศไทย สายน้ำเชี่ยวกรากท้าทายความมันส์'
    },
    {
        id:'p174',
        name:'ดอยม่อนเงาะ แม่แตง',
        alias:'นักชมทะเลหมอกและพระอาทิตย์ขึ้นแม่แตง',
        cat:'natural',
        coins:85,
        xp:100,
        stars:4.6,
        dist:58.00,
        price:'ค่ารถโฟร์วีลขึ้นดอย',
        zone:'อำเภอ แม่แตง',
        lat:19.0912, lng:98.7112,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวทะเลหมอกยอดฮิตบนดอยสูง สัมผัสอากาศหนาวและวิวดอยหลวงเชียงดาวไกลๆ'
    },
    {
        id:'p175',
        name:'น้ำตกหมอกฟ้า แม่แตง',
        alias:'นักชื่นชมม่านน้ำตกหมอกฟ้า',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.6,
        dist:54.00,
        price:'20 บาท',
        zone:'อำเภอ แม่แตง',
        lat:19.1212, lng:98.7812,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกสวยงามสายน้ำไหลตกลงมาจากหน้าผาสูง เกิดละอองน้ำฟุ้งกระจายเหมือนหมอก'
    },
    {
        id:'p176',
        name:'สวนคามิลเลีย สวนพฤกษศาสตร์แม่ริม',
        alias:'คนรักดอกไม้เมืองหนาวแม่ริม',
        cat:'natural',
        coins:65,
        xp:75,
        stars:4.5,
        dist:30.00,
        price:'40 บาท',
        zone:'อำเภอ แม่ริม',
        lat:18.8954, lng:98.8712,
        img:'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=500',
        desc:'โซนจัดแสดงดอกไม้เมืองหนาวและพรรณไม้หายากในสวนพฤกษศาสตร์'
    },
    {
        id:'p177',
        name:'น้ำตกตาดหมอก แม่ริม',
        alias:'นักเที่ยวน้ำตกป่าดิบชื้นแม่ริม',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.3,
        dist:28.50,
        price:'ฟรี',
        zone:'อำเภอ แม่ริม',
        lat:18.9212, lng:98.9112,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกธรรมชาติกลางป่าเขียวขจีในอำเภอแม่ริม บรรยากาศเงียบสงบ'
    },
    {
        id:'p178',
        name:'ปางช้างแม่สา แม่ริม',
        alias:'นักชมช้างแสดงโชว์ศิลปะแม่ริม',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.4,
        dist:27.00,
        price:'ค่าเข้าชมตามแพ็กเกจ',
        zone:'อำเภอ แม่ริม',
        lat:18.9054, lng:98.8912,
        img:'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=500',
        desc:'ปางช้างเก่าแก่ที่มีชื่อเสียง ชมการแสดงความสามารถของช้างไทย'
    },
    {
        id:'p179',
        name:'ฟาร์มงูแม่ริม (Chiang Mai Snake Farm)',
        alias:'นักชมการแสดงงูพิษแม่ริม',
        cat:'natural',
        coins:50,
        xp:60,
        stars:4.1,
        dist:24.00,
        price:'ค่าเข้าชม',
        zone:'อำเภอ แม่ริม',
        lat:18.8812, lng:98.9212,
        img:'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=500',
        desc:'ศูนย์แสดงพันธุ์สัตว์เลื้อยคลานและการแสดงงูพิษนานาชนิด'
    },
    {
        id:'p180',
        name:'คุ้งน้ำปิง แม่ริม',
        alias:'นักพักผ่อนริมน้ำปิงแม่ริม',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.4,
        dist:22.00,
        price:'ฟรี',
        zone:'อำเภอ แม่ริม',
        lat:18.8512, lng:98.9712,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'จุดชมวิวและร้านอาหารริมแม่น้ำปิงบรรยากาศร่มรื่นในอำเภอแม่ริม'
    },
    {
        id:'p181',
        name:'อ่างเก็บน้ำห้วยตึงเฒ่า แม่ริม',
        alias:'นักพักผ่อนซุ้มแพริมน้ำห้วยตึงเฒ่า',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.5,
        dist:14.00,
        price:'20 บาท',
        zone:'อำเภอ แม่ริม',
        lat:18.8512, lng:98.9512,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'อ่างเก็บน้ำยอดฮิต มีซุ้มแพริมน้ำ อาหารพื้นบ้าน และหุ่นฟางคิงคองยักษ์'
    },
    {
        id:'p182',
        name:'วัดป่าปงคอก สะเมิง',
        alias:'ผู้แสวงความสงบป่าสะเมิง',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:41.00,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8612, lng:98.7512,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดป่าบรรยากาศสงบเงียบแวดล้อมด้วยธรรมชาติป่าสะเมิง'
    },
    {
        id:'p183',
        name:'ศูนย์หัตถกรรมพื้นบ้านสะเมิง',
        alias:'นักช้อปงานคราฟต์สะเมิง',
        cat:'village',
        coins:45,
        xp:55,
        stars:4.2,
        dist:43.00,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8412, lng:98.7312,
        img:'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=500',
        desc:'แหล่งจำหน่ายสินค้าหัตถกรรมและผลิตภัณฑ์แปรรูปจากเกษตรกรสะเมิง'
    },
    {
        id:'p184',
        name:'จุดชมวิวดอยสะเมิง',
        alias:'นักชมวิวหุบเขาสะเมิง',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.4,
        dist:44.50,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8512, lng:98.7212,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวทิวทัศน์ภูเขาและไร่สวนสตรอว์เบอร์รีทั่วอำเภอสะเมิง'
    },
    {
        id:'p185',
        name:'น้ำตกแม่เลย สะเมิง',
        alias:'นักท่องน้ำตกธรรมชาติสะเมิง',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.2,
        dist:47.00,
        price:'ฟรี',
        zone:'อำเภอ สะเมิง',
        lat:18.8112, lng:98.6812,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกธรรมชาติกลางป่าลึกในอำเภอสะเมิง บรรยากาศเงียบสงบ'
    },
    {
        id:'p186',
        name:'ดอยหลวงอ่างขาง ฝาง',
        alias:'นักพิชิตยอดดอยอ่างขางชายแดน',
        cat:'natural',
        coins:110,
        xp:140,
        stars:4.8,
        dist:158.00,
        price:'ฟรี',
        zone:'อำเภอ ฝาง',
        lat:19.9512, lng:99.0212,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวสูงสุดบนดอยอ่างขาง มองเห็นทิวทัศน์ฝั่งประเทศเพื่อนบ้าน'
    },
    {
        id:'p187',
        name:'หมู่บ้านนอแล อ่างขาง ฝาง',
        alias:'นักชมฐานปฏิบัติการชายแดนอ่างขาง',
        cat:'village',
        coins:85,
        xp:100,
        stars:4.6,
        dist:159.00,
        price:'ฟรี',
        zone:'อำเภอ ฝาง',
        lat:19.9612, lng:99.0112,
        img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500',
        desc:'หมู่บ้านชาวเขาติดแนวชายแดนไทย-เมียนมา ชมฐานทหารและวิถีชีวิตชาวปะหล่อง'
    },
    {
        id:'p188',
        name:'ถ้ำเชียงดาว (ถ้ำมืด)',
        alias:'นักสำรวจถ้ำมืดประจัญบานฝาง/เชียงดาว',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.5,
        dist:71.00,
        price:'ค่าไกด์และตะเกียง',
        zone:'อำเภอ ฝาง',
        lat:19.3912, lng:98.9274,
        img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500',
        desc:'โถงถ้ำมืดสนิทภายในถ้ำเชียงดาว ตื่นตาตื่นใจกับหินงอกหินย้อยธรรมชาติ'
    },
    {
        id:'p189',
        name:'อุทยานแห่งชาติดอยผ้าห่มปก (กิ่วลม)',
        alias:'นักล่าทะเลหมอกกิ่วลมดอยผ้าห่มปก',
        cat:'natural',
        coins:120,
        xp:150,
        stars:4.9,
        dist:142.00,
        price:'50 บาท',
        zone:'อำเภอ ฝาง',
        lat:20.0712, lng:99.1412,
        img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500',
        desc:'จุดชมวิวทะเลหมอกและพระอาทิตย์ขึ้นยามเช้าบนดอยผ้าห่มปก'
    },
    {
        id:'p190',
        name:'บ่อน้ำพุร้อนไชยปราการ (เชื่อมต่อฝาง)',
        alias:'นักแช่น้ำแร่ไชยปราการ',
        cat:'natural',
        coins:55,
        xp:65,
        stars:4.3,
        dist:119.00,
        price:'ฟรี',
        zone:'อำเภอ ฝาง',
        lat:19.7912, lng:99.0212,
        img:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500',
        desc:'บ่อน้ำร้อนธรรมชาติขนาดเล็กในโซนติดต่อระหว่างฝางและไชยปราการ'
    },
    {
        id:'p191',
        name:'วัดท่าตอน (พระเจดีย์แก้ว)',
        alias:'ผู้สักการะพระเจดีย์แก้วแม่อาย',
        cat:'temple',
        coins:75,
        xp:85,
        stars:4.7,
        dist:165.50,
        price:'ฟรี',
        zone:'อำเภอ แม่อาย',
        lat:20.0422, lng:99.3922,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'องค์พระเจดีย์แก้วสีใสวิบวับบนยอดเขา ณ วัดท่าตอน อำเภอแม่อาย'
    },
    {
        id:'p192',
        name:'สวนส้มอำเภอแม่อาย',
        alias:'นักชิมส้มอร่อยแม่อาย',
        cat:'natural',
        coins:60,
        xp:70,
        stars:4.5,
        dist:161.00,
        price:'ค่าเข้าชม',
        zone:'อำเภอ แม่อาย',
        lat:20.0212, lng:99.3312,
        img:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500',
        desc:'แหล่งปลูกส้มสายน้ำผึ้งคุณภาพเยี่ยมริมแม่น้ำกกในอำเภอแม่อาย'
    },
    {
        id:'p193',
        name:'วัดป่าซาง พร้าว',
        alias:'ผู้แสวงความสงบวัดป่าพร้าว',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:96.00,
        price:'ฟรี',
        zone:'อำเภอ พร้าว',
        lat:19.3212, lng:99.2212,
        img:'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=500',
        desc:'วัดร่มรื่นเงียบสงบในอำเภอพร้าว เหมาะแก่การปฏิบัติธรรม'
    },
    {
        id:'p194',
        name:'อ่างเก็บน้ำแม่ปาน พร้าว',
        alias:'นักชมวิวอ่างเก็บน้ำพร้าว',
        cat:'natural',
        coins:50,
        xp:60,
        stars:4.2,
        dist:94.00,
        price:'ฟรี',
        zone:'อำเภอ พร้าว',
        lat:19.3512, lng:99.1712,
        img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
        desc:'แหล่งน้ำธรรมชาติและจุดพักผ่อนหย่อนใจในอำเภอพร้าว'
    },
    {
        id:'p195',
        name:'ศูนย์หัตถกรรมร่มบ่อสร้าง สันกำแพง',
        alias:'ช่างวาดลายร่มสันกำแพง',
        cat:'village',
        coins:50,
        xp:60,
        stars:4.5,
        dist:13.80,
        price:'ฟรี',
        zone:'อำเภอ สันกำแพง',
        lat:18.7632, lng:99.1132,
        img:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500',
        desc:'ศูนย์การเรียนรู้การทำร่มกระดาษสาและงานหัตถกรรมพื้นบ้านสันกำแพง'
    },
    {
        id:'p196',
        name:'ตลาดสดสันกำแพง',
        alias:'นักชิมอาหารพื้นเมืองสันกำแพง',
        cat:'food',
        coins:35,
        xp:45,
        stars:4.2,
        dist:14.50,
        price:'ฟรี',
        zone:'อำเภอ สันกำแพง',
        lat:18.7412, lng:99.1212,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'ตลาดท้องถิ่นจับจ่ายสินค้าพื้นบ้านและอาหารเหนือรสชาติดั้งเดิม'
    },
    {
        id:'p197',
        name:'มหาวิทยาลัยแม่โจ้ สันทราย',
        alias:'นักชมมหาวิทยาลัยเกษตรศาสตร์เก่าแก่',
        cat:'village',
        coins:40,
        xp:50,
        stars:4.4,
        dist:14.00,
        price:'ฟรี',
        zone:'อำเภอ สันทราย',
        lat:18.8912, lng:98.9954,
        img:'https://images.unsplash.com/photo-1566127444979-b3d2b65463d7?w=500',
        desc:'มหาวิทยาลัยเกษตรศาสตร์เก่าแก่ บรรยากาศร่มรื่น พื้นที่กว้างขวาง'
    },
    {
        id:'p198',
        name:'ตลาดรวมโชค สันทราย',
        alias:'นักชิมสตรีทฟู้ดย่านสันทราย',
        cat:'food',
        coins:35,
        xp:45,
        stars:4.3,
        dist:8.00,
        price:'ฟรี',
        zone:'อำเภอ สันทราย',
        lat:18.8212, lng:99.0112,
        img:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',
        desc:'ศูนย์รวมอาหารอร่อยและตลาดนัดชื่อดังย่านสันทราย-รวมโชค'
    },
    {
        id:'p199',
        name:'อุทยานแห่งชาติแม่วาง (น้ำตกตาดหมอก)',
        alias:'นักเที่ยวน้ำตกแม่วางป่าลึก',
        cat:'natural',
        coins:70,
        xp:80,
        stars:4.4,
        dist:43.00,
        price:'20 บาท',
        zone:'อำเภอ แม่วาง',
        lat:18.5812, lng:98.7412,
        img:'https://images.unsplash.com/photo-1432405972618-fb60b0ceb067?w=500',
        desc:'น้ำตกสวยงามในเขตอุทยานแห่งชาติแม่วาง บรรยากาศป่าดิบชื้นอุดมสมบูรณ์'
    },
    {
        id:'p200',
        name:'วัดบ้านปง สันทราย/หางดง',
        alias:'ผู้สักการะวัดบ้านปง',
        cat:'temple',
        coins:45,
        xp:55,
        stars:4.3,
        dist:18.00,
        price:'ฟรี',
        zone:'อำเภอ หางดง',
        lat:18.7312, lng:98.8812,
        img:'https://images.unsplash.com/photo-1584811644163-6e491c10d744?w=500',
        desc:'วัดชนบทเงียบสงบในเขตอำเภอหางดง สถาปัตยกรรมล้านนาโบราณ'
    }
];